### ISSUE TITLE
Bug: Event "fee" contains the total fee submitted, not the base fee paid

### ISSUE THREAD

**Issue by minxylynx** [provenance-io/provenance#1002]
## Summary of Bug

When searching for an event to derive the base fee paid, for successful transactions, there is a "base_fee" event. However, it is omitted for failed transactions. It would be nice to include that event on failures for easy reference.

## Version

v1.11.1

## Steps to Reproduce

Example failure tx https://explorer.test.provenance.io/tx/8D13E31353FE788BCA231E81064B5FABB44C4DDB5EF5F7C55DE608FAE125FE71
Example success tx https://explorer.provenance.io/tx/682D65BE2C41407DDA335B95DA1D5030CE6654CEFA294897F139170389D96DFA

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
This was fixed with PR #1107 (and https://github.com/provenance-io/cosmos-sdk/pull/268).
