### ISSUE TITLE
Denom for Fee and Staking are hard coded

### ISSUE THREAD

**Issue by arnabmitra** [provenance-io/provenance#1067]
## Summary

Denom for Fee and Staking are hard coded

## Problem Definition
Denom for Fee and Staking are hard coded to `nhash`,  also MsgFees are hard coded to charge base fees in `nhash`, if we want to run side chains/zones we would probably want to customize them to have a different staking token and a fee token.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
This is a prime candidate for #962
