### ISSUE TITLE
Support expiration functionality for scopes

### ISSUE THREAD

**Issue by derekadams** [provenance-io/provenance#1073]
## Summary

Add support for expiration of scopes via the expiration module.

## Problem Definition

What problems may be addressed by introducing this feature?
Scopes that are no longer needed take up memory in the head state and may be purged in order to improve performance.

What benefits does the Provenance Network stand to gain by including this feature?
Smaller head state for better performance.

## Proposal

- Add `--expires` flag to existing scope creation which will allow the expiration to be set via the CLI. If no expiration is provided, a reasonable default will be set.
- Add new message that will be processed in order to expire a scope asset. This will be handled separately from the delete message since the logic may be different (e.g. leaving headstones for expired assets rather than completely deleting them)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by egaxhaj** [comment]
Closed in #1084
