### ISSUE TITLE
Update proto REST definitions

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1077]
## Summary

Review the `service`s in our proto files and make sure REST endpoints are generated appropriately.

## Problem Definition

With Cosmos-SDK v0.46, the deprecated REST stuff was finally removed. Now, the protobuf auto-generated code from the services is how to define the REST endpoints. So some of our REST endpoint code has been removed. We need to make sure that functionality is maintained though.

## Proposal

Compare the old REST stuff that was removed, and make sure things are defined in the protos such that functionality is maintained.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
I don't believe that any tx type msgs are supported via rest (and I don't believe they have been in the past either). 

Curious how these could have been tested properly...

**Comment by SpicyLemon** [comment]
The following REST endpoints have been removed in favor of their `/provenance/...` counterparts. There are many more queries under `/provenance/...`. These are just ones that were removed.
* `GET` `attribute/{address}/attributes` -> `/provenance/attribute/v1/attributes/{address}`
* `GET` `attribute/{address}/attributes/{name}` -> `/provenance/attribute/v1/attribute/{address}/{name}`
* `GET` `attribute/{address}/scan/{suffix}` -> `/provenance/attribute/v1/attribute/{address}/scan/{suffix}`
* `GET` `marker/all` -> `/provenance/marker/v1/all`
* `GET` `marker/holders/{id}` -> `/provenance/marker/v1/holding/{id}`
* `GET` `marker/detail/{id}` -> `/provenance/marker/v1/detail/{id}`
* `GET` `marker/accesscontrol/{id}` -> `/provenance/marker/v1/accesscontrol/{id}`
* `GET` `marker/escrow/{id}` -> `/provenance/marker/v1/escrow/{id}`
* `GET` `marker/supply/{id}` -> `/provenance/marker/v1/supply/{id}`
* `GET` `marker/assets/{id}` -> `/provenance/metadata/v1/ownership/{address}` (you can get the `{address}` from `/provenance/marker/v1/detail/{id}`).
* `GET` `name/{name}` -> `/provenance/name/v1/resolve/{name}`
* `GET` `name/{address}/names` -> `/provenance/name/v1/lookup/{address}`

The following REST endpoints have been removed. They do not have any REST replacement counterparts. Use GRPC instead.
* `DELETE` `attribute/attributes` -> `DeleteAttribute(MsgDeleteAttributeRequest)`
* `POST` `/marker/{denom}/mint` -> `Mint(MsgMintRequest)`
* `POST` `/marker/{denom}/burn` -> `Burn(MsgBurnRequest)`
* `POST` `/marker/{denom}/status` -> One of:
  * `Activate(MsgActivateRequest)`
  * `Finalize(MsgFinalizeRequest)`
  * `Cancel(MsgCancelRequest)`
  * `Delete(MsgDeleteRequest)`

**Comment by SpicyLemon** [comment]
Some more REST endpoint changes have been found due to Cosmos changes in v0.46:

There were some convenient short-form `GET` endpoints that were removed in favor of longer ones:
* `/node_info` -> `/cosmos/base/tendermint/v1beta1/node_info`
* `/syncing` -> `/cosmos/base/tendermint/v1beta1/syncing`
* `/blocks/latest` -> `/cosmos/base/tendermint/v1beta1/blocks/latest`
* `/blocks/{height}` -> `/cosmos/base/tendermint/v1beta1/blocks/{height}`
* `/validatorsets/latest` -> `/cosmos/base/tendermint/v1beta1/validatorsets/latest`
* `/validatorsets/{height}` -> `/cosmos/base/tendermint/v1beta1/validatorsets/{height}`

Also, the denom owners `GET` endpoint changed from `/cosmos/bank/v1beta1/denom_owners/{denom}` to `/cosmos/bank/v1beta1/supply/by_denom?denom={denom}`.

**Comment by iramiller** [comment]
We could maintain long term or not... we should definitely list this changes in our changelog api notes though.
