### ISSUE TITLE
Remove or Refactor the Queriers

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1078]
## Summary

Investigate whether or not we still need the queriers (e.g. `x/attribute/keeper/querier.go`) and remove they're not needed.

## Problem Definition

The primary use of the queriers was the REST endpoints that were removed with Cosmos-SDK v0.46. Those queriers contain a lot of duplicate logic and are missing some functionality (e.g. metadata record specs). I know that one thing they do is cause the creation of REST endpoints under the `/custom/` path. I don't know if there's anything else they do though.

We should look into what all they do and see if we need to keep them around anymore. If all they do is create those REST endpoints, then we can remove them because GRPC Gateway creates REST endpoints from the protos for all the queries we need.

## Proposal

Investigate the `sdk.Querier` stuff to identify functionality that defining them provides.

If all functionality is already covered by other stuff that we already have, remove them.

If there's functionality that we still need, audit our current queriers to identify any pieces that we are missing, create a ticket to: 1. add those missing pieces, and 2. refactor them to create the query `Msg`s and use the keeper's query functions (instead of having their own logic for the queries).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
In Cosmos-SDK, from `v0.46.1` to `main` (as of commit `252c67361` and Sept 20, 2022, 8:22 PM UTC), all the `keeper/querier.go` files have been removed. There's still `querier.go` files defined in some of the `types` folders, probably holding just some string definitions.

**Comment by iramiller** [comment]
related: it would be useful if we could remove some of the indexes/keys that are associated with some of these removed queries in order to reduce the size of our data store further.

**Comment by SpicyLemon** [comment]
As of `v1.19.0-rc2`, the queriers have all been removed!
