### ISSUE TITLE
Add ability to convert p8e ContractSpec to new ContractSpecification and RecordSpecifications.

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#113]
## Summary

Add a special Create method that takes a P8e ContractSpec and parses into ContractSpecification and RecordSpecifications.

## Problem Definition

The P8e system generates a complete contract specification using a Kotlin class as a starting point during a build process.  This contract specification output contains a full collection of inputs used by the class as well as a collection of consideration/constraints.  The type formats are all slightly different than an on chain ContractSpecification as P8e uses a set of nested, repeated Definitions for several different purposes.

The `legacy/v040/migrate.go` file contains an implementation that maps from a legacy v039 contractspec to the current ContractSpecification and RecordSpecifications.  A discussion with the P8e team on how they wish to support recording the spec going forward is required.  If they are willing to change their format to match the current one then no further work is required.  If the `v0` format is required then a new AddP8eContractSpec method will need to be created that take the v0 format objects and processes them into the current form.

- [ ] Add a special Create method that takes a P8e ContractSpec and parses into ContractSpecification and RecordSpecifications.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
An implementation for this process exists in the legacy migration functions.
https://github.com/provenance-io/provenance/blob/401c6d8acba9e1cf85dc7ec0a2e56804b816f949/x/metadata/legacy/v040/migrate.go#L354

**Comment by piercetrey-figure** [comment]
After discussing with the @provenance-io/p8e team, yes this is indeed still something that we will need as there would be too many changes needed on our side to get done in the near-term

**Comment by iramiller** [comment]
> After discussing with the @provenance-io/p8e team, yes this is indeed still something that we will need as there would be too many changes needed on our side to get done in the near-term

That was never really the question I was looking to have @channa-figure get answered ... the part we need to know/ensure is that the implementation of this feature lines up with what p8e is expecting.

**Comment by scirner22** [comment]
I'm confused what this issue relates to. I thought the last pbc release contained everything p8e needed to migrate from simple client to pbc 2.0 grpc?

**Comment by iramiller** [comment]
All the base types and specification components are implemented and there are grpc query endpoints for reading/writing these various pieces as well as validation/integration tests covering their implementations.  If P8e were starting on integrating with the blockchain the endpoints needed are there.

What is not in there are endpoints to support the removed apis that P8e is using on the v039 chains via simple client.  There are really two methods used by P8e right now, memorialize contract and add contract specification... We expect that P8e will have to make changes moving to grpc so these two methods have been saved for when that integration happens so the implementations can match.  The plan is for those implementations to ship in the 0.3.0 release but for that to happen the collaboration needs to occur to ensure both sides of the api match up.
