### ISSUE TITLE
Enable ICA Controller and add ICA auth module.

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1171]
## Summary

The purpose of this is to enable the Controller portion of the ICA module, and to add a generic auth module that other modules can call to perform ICA transactions.

## Problem Definition

There is currently no way for the Provenance Blockchain to use the ICA Controller to interact with other chains.

## Proposal

- Enable the controller within the upgrade handler.
- Introduce a generic auth module that can register interchain accounts and send transactions.
- The module should be usable by other modules.
- The module should not be exposed to users of the cli.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
No longer needed because of built-in stuff.
