### ISSUE TITLE
(DEV Task) - Tests for ICA msgs, cli, and helper functions

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/provenance#1203]
## Summary

Tests are needed for two new msgs in the `x/marker/types` module these are `MsgReflectMarkerRequest` and `MsgIcaReflectMarkerRequest` for their `ValidateBasic` methods.  Also, check for any other property that can be validated that currently is not.

Tests for the `x/marker/cli` command `reflect`.

Tests for helper method `filterAccessList` in the `x/marker/msg_server.go`.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by arnabmitra** [comment]
done
