### ISSUE TITLE
Node sync stopped at 8485555

### ISSUE THREAD

**Issue by Palak3196** [provenance-io/provenance#1252]
Hi team,
My provenance mainnet node is stuck on blockheight 8485555. I was using provenanceio/provenance:v1.12.0

Shall I run the node with v1.13.0 to resume sync?
docker run --rm -it --name node-prov -p 1317:1317 -p 26657:26657 -p 9090:9090 -v /provenance-arch-node:/home/provenance provenanceio/provenance:v1.13.0 provenanced start

I'm confused because v1.13.0 and v1.12.2 are scratched out here: https://explorer.provenance.io/network/upgrades

**Comment by Palak3196** [comment]
I was using v1.12.0 with docker: `docker run --rm -it --name node-prov -p 1317:1317 -p 26657:26657 -p 9090:9090 -v /provenance-arch-node:/home/provenance provenanceio/provenance:v1.12.0 provenanced start`

At 8485555, I tried to upgrade the node by stopping the above container and starting the node with below command:
`docker run --rm -it --name node-prov -p 1317:1317 -p 26657:26657 -p 9090:9090 -v /provenance-arch-node:/home/provenance provenanceio/provenance:v1.13.0 provenanced start`
But its running into this error:
```
1:32PM INF Successfully upgraded to: ochre with version map: map[attribute:2 auth:3 authz:2 bank:4 capability:1 crisis:1 distribution:2 evidence:1 feegrant:2 genutil:1 gov:3 group:1 ibc:2 interchainaccounts:1 marker:2 metadata:3 mint:1 msgfees:1 name:2 params:1 reward:1 slashing:2 staking:3 transfer:2 upgrade:2 vesting:1 wasm:1]
panic: Value missing for hash 1131c63f38d5cdb6dac9c0c0b2631d241fb20b17e4a6cff9f9fb43f79dc7639e corresponding to nodeKey 6e1131c63f38d5cdb6dac9c0c0b2631d241fb20b17e4a6cff9f9fb43f79dc7639e

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Get(0xc000f89340, {0xc02d7df320, 0x1e, 0x30})
        github.com/cosmos/cosmos-sdk@v0.46.4/store/iavl/store.go:214 +0x10d
github.com/cosmos/cosmos-sdk/store/cache.(*CommitKVStoreCache).Get(0xc013199db8, {0xc02d7df320, 0x1e, 0x30})
        github.com/cosmos/cosmos-sdk@v0.46.4/store/cache/cache.go:111 +0xc5
```

**Comment by iramiller** [comment]
We have been doing some in-depth research on what caused this issue during our last upgrade ... it seems that the `cleveldb` driver for the state store interacts poorly with the `panic` method the upgrade module uses to halt the chain for the upgrade.  We are working on some procedures for a switch to the `goleveldb` which does not exhibit these behaviors.  For others that hit the issue above using the `--halt-height=8485554` flag to provide for a clean shutdown of the node prior  to the upgrade height followed by restarting without this flag to allow the node to run to the upgrade height for a normal swap to the 1.13.0 binary will result in a successful transition through the upgrade.  This is because the standard halt height flag results in a clean shutdown of the binary with all pending transactions cleanly written to disk.

**Comment by Palak3196** [comment]
Thanks for the update Ira, appreciate your explaining the cause.

So I have 2 nodes right now- 1st is the one that I stopped at 8485554.
And the 2nd is a new node that I setup using the latest snapshot here: https://provenance.io/quicksync.

For this second node, I was able to get it syncing 8485554 onwards with v1.13.0
Command used: `docker run --rm -it --name node-prov -p 1317:1317 -p 26657:26657 -p 9090:9090 -v /provenance-arch-node-new:/home/provenance provenanceio/provenance:v1.13.0 provenanced start`

However, the issue with this new node is that it doesn't respond to the curl query to fetch latest block. I'm using: 
`curl -X GET http://10.x.x.x:1317/blocks/latest -H "accept: application/json"`

Would you have any other curl that will give me the latest block height the node is at?

**Comment by iramiller** [comment]
The release notes for 1.13 outline all of the changes to the api endpoints. https://github.com/provenance-io/provenance/releases/tag/v1.13.0

**Comment by Palak3196** [comment]
Oh my bad, I didn't check these.
Thanks for the update.

The new curl queries are working fine now.

I could also get my first node to start working after using start  --halt-height=8485554 approach.
You may close this thread.

Again, really appreciate your help with all this!
