### ISSUE TITLE
gov-tx.go in wasmd needs a flag added

### ISSUE THREAD

**Issue by arnabmitra** [provenance-io/provenance#1254]
## Summary of Bug
Craig Berry(Figure) while trying to submit a wasm-store gov proposal found that we get this error 
```
pd --home=build/node0 -t tx gov submit-legacy-proposal wasm-store dcc.wasm --title "Store DCC Smart Contract" --description "Faciliate mint/burn/transfer of restricted marker between consortium of banks" --run-as $(pd keys show -a bank1 -t --home build/node0) --instantiate-everybody "true" --deposit "1nhash" --from bank1

Error: flag any of: flag accessed but not defined: instantiate-anyof-addresses
```
this has been fixed here https://github.com/CosmWasm/wasmd/pull/1084 , we need it on our notional wasm fork

This only affect cli so is minor fix imo, but it does prevent cli users from submitting wasm store on testnet/mainnet.

## Version
v1.13.0

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
This flag has been added to our branch.
