### ISSUE TITLE
MsgFees Module 50/50 Fee Split on MsgAssessCustomMsgFeeRequest Removal

### ISSUE THREAD

**Issue by hyperschwartz** [provenance-io/provenance#1263]
## Summary

The current process for assessing a custom fee via the `MsgAssessCustomMsgFeeRequest` msg takes 50% of the amount charged and sends it to Provenance.  This fee should be removed.

## Problem Definition

This is a planned change, and this issue is to ensure that this change is tracked.

## Proposal

The code that currently subtracts 50% of the fees sent should be removed, and the comments on the `MsgAssessCustomMsgFeeRequest` in the proto definition stating that this behavior in place should be removed.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Was finished with PR https://github.com/provenance-io/provenance/pull/1267
