### ISSUE TITLE
Add wasm support for writing sessions, records, and object store info

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1279]
## Summary

In the metadata module, add support for WriteSession, WriteRecord, BindOSLocator, ModifyOSLocator.

## Problem Definition

As a smart contract creator, I want to be able to write/update sessions and records so that I can more easily manage them.

## Proposal

Update the metadata module's wasm stuff to allow for writing sessions and records.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Notes from a discussion between myself, Ira, and Ken:

```plaintext
update wasmd:
    New encoder type that will provide the sender and the contract to the encoder.

Update metadata:
    For each signer:
        Pull the account. If it's sequence zero, the role must be PROVENANCE.
        If sequence > 0, you can't be PROVENANCE type.
    Finish building out the metadata wasmd stuff.
        Ideally, we could just reuse all the types we already have that are generated from the protos and/or defined in `types`.

Special case:
    Write scope can happen with accounts that have a sequence 0 but aren't meant for the PROVENANCE role.
        In such cases, just let it error. Make them sign a Tx.
```

**Comment by iramiller** [comment]
Upon further research of the `wasmd` module ... we will not require a fork to add support for the pass through signer as a second signature/from parameter.  We will want to change the wiring of our wasmd module to use a custom handler chain and add a special handler for metadata messages. 

https://github.com/cosmwasm/wasmd/blob/a925a9ed61752c335c66964ec4241dac5cb0ff70/x/wasm/keeper/handler_plugin.go#L35

with a message handler chain that includes our custom handler.

**Comment by SpicyLemon** [comment]
I created #1381 to enforce the `PROVENANCE` role/smart contract thing. The remainder of this issue will be enabling smart contracts to use the various metadata module endpoints.

**Comment by SpicyLemon** [comment]
The remainder of this issue should be covered by https://github.com/provenance-io/provwasm/issues/101
