### ISSUE TITLE
Create tool for comparing underlying database contents as basis for identifying app hash mismatches

### ISSUE THREAD

**Issue by derekadams** [provenance-io/provenance#1282]
## Summary

When nodes encounter application hash mismatches, it is not easy to determine which data differs in order to trace the issue. A tool that offers a low-level key/value comparison of two database files (e.g. `application.db`) would allow the differences to be determined using only the raw database files. This would only be relevant for node data at relatively the same height, but it should work nicely in cases where there is a known issue and good/bad versions of the data at relatively similar heights.

## Problem Definition

We currently do not have a method of determining the reason for an app hash mismatch since the database data is opaque unless it's being loaded from within the context of the cosmos application. 

## Proposal

Build a simple key/value comparison tool that notes differences between the low-level databases so they can be traced to find the cause of an app hash mismatch. The initial version will be targeted to leveldb backends (`goleveldb` and `cleveldb`), but the `tm-db` library will be used so that other backends may be supported as well.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Based on the results of this research it seems we will need to go a different direction.  There is simply too much change noise in the output
