### ISSUE TITLE
Comments reversed between GetSingers and GetSignerBytes in multiple modules

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#1294]
This comment looks to be reversed with the comment on `GetSignerBytes` method in `ln:89`.
```suggestion
// GetSigners indicates that the message must have been signed by the address provided
```

_Originally posted by @egaxhaj in https://github.com/provenance-io/provenance/pull/1285#discussion_r1066230382_

**Comment by SpicyLemon** [comment]
The `GetSignerBytes` funcs were all removed with #1304. They're part of the `LegacyMsg` interface, but not the `Msg` interface; they're not needed anymore.

So I'm pretty sure it's safe to close this. Feel free to reopen if there's more to do.
