### ISSUE TITLE
Ability to add n markers using one gov proposal

### ISSUE THREAD

**Issue by ghost** [provenance-io/provenance#1296]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
The `gov.v1.MsgSubmitProposal` allows a proposal to contain multiple messages. Is that enough to cover the needs of this issue?
