### ISSUE TITLE
Add better logging around store creation / deletion / etc in app/upgrade/upgrade.go

### ISSUE THREAD

**Issue by mtps** [provenance-io/provenance#130]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Related to #139

**Comment by fkneeland-figure** [comment]
The code to solve this has already been added here: https://github.com/provenance-io/provenance/blob/545033b09c9cc9ba2bfbf549caa47c79729eac74/app/upgrades.go#L203-L210
