### ISSUE TITLE
Add CLI for Sanction Gov Props

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1311]
## Summary

Add CLI commands for creating and submitting the sanction module's governance proposals.

## Problem Definition

The sanction module's governance proposal endpoints don't have any CLI helpers. With `gov.v1`, adding commands to `tx gov` is deprecated in favor of `tx` commands in the respective modules that send a `MsgSubmitProposal`. These commands weren't in the initial sanction module though.

## Proposal

Add commands for each sanction module endpoint under `tx sanction ...`.

* The commands should create their respective `Msg`, then wrap it in a `MsgSubmitProposal` and send that.
* The `authority` should be populated automatically. There is no reason to ever have it be something other than the one magic value.
* There should be a `--deposit` flag for indicating the amount of deposit to include initially.
* There should be a `--metadata` flag for populating the proposal's metadata.
* If they've been added to the `MsgSubmitProposal` by the time this issue is addressed, there should also be `--title` and `--description` flags for those two proposal fields.
* The sanction and unsanction commands should just take in the list of addresses.
* The update params command should take in the two coins amounts.
* The help text for each should indicate that it's submitting a governance proposal.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
This was completed with PR https://github.com/provenance-io/cosmos-sdk/pull/510
