### ISSUE TITLE
New endpoint for updating a scope's value owner address.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1329]
## Summary

Create a new `UpdateValueOwner` endpoint for updating a scope's value owner address field.

## Problem Definition

As a scope owner, I want to be able to update its `value_owner_address` field, without needing to make a call to `WriteScope`, in order to make it easier to do and also not have to pay the `WriteScope` msg-based fee.

As the owner of many scopes, I want to be able to update their `value_owner_address` fields all to the same value, without needing to make a call to `WriteScope`, in order to make it easier and cheaper to do so.

## Proposal

Create an `UpdateValueOwner` endpoint in the metadata module. It should take in a list of scope ids, new value owner, and list of signers. It doesn't need to output anything. Signer validation needs to be the same as when using `WriteScope` to only update the `value_owner_address` field. Validation should be done only once for each unique existing value owner, and once for the new value owner (as opposed to once per scope).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
If you are merging loan pools it probably makes sense to be able to move all scopes with one value_owner into another value_owner... This probably makes sense as another similar endpoint. (merge value owners)
