### ISSUE TITLE
Create a bot account for the Org that can facilitate signing commits and creating PRs

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#1380]
## Summary

Add functionality to CI workflows to sign commits and automatically create PRs.

## Problem Definition

When PRs are merged to `main`, certain workflows will run that can trigger creating new PRs based on code differences. Because Provenance requires signed commits, any PRs created by automatic workflows need to be signed as well to be accepted.

## Proposal

As it stands the current process (take a look at #1339) is to have members on the core team add additional GPG keys that can be used by workflows to be able to auto sign commits and submit PRs against main. This also requires adding the GPG private key and passphrase as GitHub secrets.

To better improve the key management process I propose one of the options below.
1. We create a separate GitHub account that we can use for the sole purpose of signing commits and submitting PRs in our CI workflows. This is a community accepted approach. One drawback here is that it takes up a seat in the organization.
3. We create a GitHub app for the organization that can help facilitate in signing and submitting PRs in workflows.
4. We use the web UI API and have GitHub automatically sign the commits and submit the PRs.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Isn't this complete now?

**Comment by egaxhaj** [comment]
No. In #1374 we set it to use your personal GitHub account to sign commits and submit PRs but it also excludes that person from approving the PR. This proposal eliminates the need to use a personal account.

**Comment by egaxhaj** [comment]
:done:

- created a bot account to replace the user accounts used in signing commits in our CI process.
