### ISSUE TITLE
Restrict the `PROVENANCE` role.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1381]
## Summary

The `PROVENANCE` role is designed to represent smart contracts. We need to require smart contracts to use that role, and only allow smart contracts to use that role.

## Problem Definition

In order to start using smart contracts for metadata module stuff, we want to restrict them to the `PROVENANCE` role and restrict the `PROVENANCE` role to only smart contracts.

```
  // PARTY_TYPE_PROVENANCE is used to indicate this party represents the blockchain or a smart contract action
  PARTY_TYPE_PROVENANCE = 8;
```

## Proposal

During party/role validation (in the metadata module), for each party, get the account (e.g. `k.accountKeeper.GetAccount(ctx, addr)`).
* If the role is `PROVENANCE`, the account must have `GetSequence() == 0` and `GetPubKey() == nil`.
* If `GetSequence() == 0` and `GetPubKey() == nil`, the role must be `PROVENANCE`.

This account logic matches what's in the `wasm` module: https://github.com/provenance-io/wasmd/blob/88e01a98ab8a87b98dc26c03715e6aef5c92781b/x/wasm/keeper/keeper.go#L246-L254

Duplicating logic usually isn't the best thing to do, but in this case, it's probably the easiest way. The accounts the module creates are standard accounts, so we can't test them for type. We might be able to use the wasm keeper's `HasContractInfo`, but then we'd have to add that to the metadata module/keeper, which is usually something to avoid.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
I think the `seq = 0` and `nil pub_key` checks make a lot of sense for this check ... even if an account could potentially exist later on if the message arrives in our module ahead of any signatures being made for it the protocol would have to be the one performing the action.
