### ISSUE TITLE
Implement Merge Queues in Provenance CI flow

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#1387]
## Summary

It would be very beneficial for Provenance to be able to leverage Github [Merge Queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

## Problem Definition

Sometimes merges and auto-merges to main cause the changelog and other docs to get misaligned (i.e: unreleased changes end up in released changelog entries). This can be preventable by leveraging GitHub's [Merge Queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue). Other times, certain PRs need to be merged first before subsequent PRs are merged but this is not clear on the PRs dashboard.

## Proposal

I propose we implement [Merge Queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) when submitting PRs to be able to group them together. Two key benefits we gain from this is that follow up PRs will contain the base_branch changes plus previous PR changes ahead of it.

> The merge queue creates temporary branches with a special prefix to validate pull request changes. The changes in the pull request are then grouped into a merge_group with the latest version of the base_branch as well as changes ahead of it in the queue. GitHub will merge all these changes into base_branch once the checks required by the branch protections of base_branch pass.

> After grouping a pull request with the latest version of the target branch and changes ahead of it in the queue, if there are failed required status checks or conflicts with the base branch, GitHub will remove the pull request from the queue. The pull request timeline will display the reason why the pull request was removed from the queue.

In addition, we can trigger GitHub Actions on the entire group with the `merge_group` action trigger.

```yaml
on:
  pull_request:
  merge_group:
```

Other benefits are:
- dependabot PRs
- renovate PRs
- backporting
- milestones
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
We might also consider telling git to use a `union` merge strategy for the `CHANGELOG.md` file: https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitattributes.html#_built_in_merge_drivers

> Run 3-way file level merge for text files, but take lines from both versions, instead of leaving conflict markers. This tends to leave the added lines in the resulting file in random order and the user should verify the result. Do not use this if you do not understand the implications.

In `.gitattributes`:
```
CHANGELOG.md merge=union
```

That would prevent any conflicts, but might end up messing up the changelog sometimes. But it's something to look into.
