### ISSUE TITLE
Fix bad log message in app/upgrade.go

### ISSUE THREAD

**Issue by mtps** [provenance-io/provenance#140]
## Summary of Bug

`2:17PM INF Store upgrades height=585800 plan=v0.2.0 upgrade="marshaling error: json: unsupported type: types.UpgradeHandler"`

Add MarshalJson for appUpgrade in `app/upgrades.go` so log message makes more (useful) sense.

## Version

v0.2.0

## Steps to Reproduce

First block after an upgrade creates the message. There is no negative consequence of it occurring.
____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by fkneeland-figure** [comment]
This has already been solved in: https://github.com/provenance-io/provenance/commit/924858c16e9f62224ea8c09fa920a800128d462f#diff-aeec7ddb4cf8b7e9e6e57625770d369cce5f377cc350b42c3aca0427bba8dfbcL64

I also tested the upgrades with my own local branch: https://github.com/provenance-io/provenance/compare/fredstest?expand=1 and verified that when I do a successful upgrade locally I can see the correct print statement for the Store upgrades: 
<img width="1198" alt="Screen Shot 2021-09-28 at 5 23 57 PM" src="https://user-images.githubusercontent.com/86616427/135178718-6be9c5e6-c593-4f79-ad68-de34d0522f90.png">

**Comment by fkneeland-figure** [comment]
So I think we can close this issue without a pr.  FYI @iramiller

**Comment by fkneeland-figure** [comment]
Here is the pr it was addressed in: https://github.com/provenance-io/provenance/pull/170
