### ISSUE TITLE
Implement restrictions in our v0.46-based SDK fork

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1415]
## Summary

Apply https://github.com/cosmos/cosmos-sdk/pull/14224 to `main-pio` in our SDK fork.

## Problem Definition

We've got several things that can utilize those `SendRestrictions`. We should bring them into our fork so we can start using them and clean up other customizations in our fork.

## Proposal

* Update `InputOutputCoins` to accept a single `Input` (instead of slice). In `MultiSend`, return an error if there isn't exactly 1.
* Implement the `SendRestriction`s like in https://github.com/cosmos/cosmos-sdk/pull/14224
* Remove the injectable custom keepers that we've added (e.g. `SanctionKeeper`).
* Refactor the sanction and quarantine modules to inject restrictions.
* Be sure to note stuff under "API Breaking" in the changelog.

We'll update the provenance repo stuff later, when we do a bump.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
In a discussion today the topic of UTXO came up ... and I realized that the multiple input/output design probably came from someone copying what has been done in a UTXO chain world ... and that simply doesn't make sense for our system.
