### ISSUE TITLE
Archive our cosmovisor repo

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1420]
## Summary

Archive our [cosmovisor](https://github.com/provenance-io/cosmovisor) repo.

## Problem Definition

We originally created our https://github.com/provenance-io/cosmovisor repo to add a couple features that are now part of the official version. It is also out of date and missing some stuff.

## Proposal

Update that repo's README to indicate that it's not to be used anymore. Also provide instructions on switching from ours to theirs; I believe a couple env vars are slightly different (at the very least). Once that's done, archive the repo.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
This is long over due... while we are at it we should consider removing any docker images that were making use of this.

**Comment by SpicyLemon** [comment]
1. I updated the readme to state that it's archived and provide migration instructions (to the SDK's version).
2. I also had Phil log into dockerhub and delete the `provenanceio/cosmovisor` image.
3. I then went into the https://github.com/provenance-io/cosmovisor settings and archived the repo.
