### ISSUE TITLE
Add IBC rate limiting protection system

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#1498]
## Summary

Add the [Osmosis IBC rate limiting](https://github.com/osmosis-labs/osmosis/tree/main/x/ibc-rate-limit) protection to the Provenance project

## Problem Definition

The IBC Rate Limit module is responsible for adding a governance-configurable rate limit to IBC transfers. This is a safety control, intended to protect assets on osmosis in event of:

- a bug/hack on osmosis
- a bug/hack on the counter-party chain
- a bug/hack in IBC itself

This is done in exchange for a potential (one-way) bridge liveness tradeoff, in periods of high deposits or withdrawals.

## Proposal

Wire in the Osmosis IBC rate limiting system.  Ensure that the chain functions normally when the smart contract referenced is not available.  Prepare a smart contract implementation for subsequent governance inclusion into Provenance to configure these limits.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Taztingo** [comment]
The stride team was inspired by Osmosis and created their own implementation. They do all their logic in their ratelimit module rather than passing it to a smart contract.

https://github.com/Stride-Labs/stride/tree/main/x/ratelimit

**Comment by Taztingo** [comment]
Also, Axelar has their own implementation https://github.com/axelarnetwork/axelar-core/tree/main/x/axelarnet

**Comment by iramiller** [comment]
Very interesting. The smart contract version should be more mutable for responding to future configuration needs… but an in protocol version is likely more efficient. 

@Taztingo have you done any testing on these approaches? What is your preference (if any) so far?

**Comment by Taztingo** [comment]
I haven't tested any of them yet, and just happened to stumble across them. The Osmosis one is listed as an official ibc-app, which is making me lean towards that solution. https://github.com/cosmos/ibc-apps#ecosystem-apps

**Comment by Taztingo** [comment]
Putting this in hold until we get a good solution. We will either have to manage our own module(s) that are a replica of the other solutions or wait until an existing solution can be imported.
