### ISSUE TITLE
Add support to ADD/UPDATE/REMOVE required attributes for a restricted marker.

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/provenance#1512]
## Summary

Add support to change the required attributes on a restricted marker via gov proposal or a tx from an account with transfer authority.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Sure, gov proposal is a useful way to do this ... but someone with `transfer` granted to them should be able to edit these values at anytime...

**Comment by nullpointer0x00** [comment]
Good point.  I will modify this issue to include that.
