### ISSUE TITLE
Unable to query all governance proposals

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1554]
## Summary of Bug

The user is unable to query for the proposals when an AddMarkerProposal exists.

## Version

1.15

## Steps to Reproduce

Query a blockchain for proposals that contains the AddMarkerProposal such as mainnet.
```
provenanced q gov proposals --node=https://rpc.provenance.io:443
```

Results:
```
Error: rpc error: code = Unknown desc = rpc error: code = Internal desc = no concrete type registered for type URL /provenance.marker.v1.AddMarkerProposal against interface *v1beta1.Content: unknown request
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
We removed the `AddMarkerProposal` from the protos. Therefore, it's no longer registered with the codec. So when a node tries to read a proposal with one of those in it, it doesn't know what to do.

I'm pretty sure there were a few messages removed from the protos for v1.15.0. We'll want to identify which ones and probably add them back in.

**Comment by SpicyLemon** [comment]
Proto stuff removed with `v1.15.0`:
The marker `AddMarkerProposal` message.
The `proto/provenance/metadata/v1/p8e/p8e.proto` file.
The `MsgWriteP8eContractSpecRequest` and `MsgWriteP8eContractSpecResponse` messages (and `WriteP8eContractSpec` endpoint).
The `MsgP8eMemorializeContractRequest` and `MsgP8eMemorializeContractResponse` messages (and `P8eMemorializeContract` endpoint).

We'll probably need to put all those messages back in and add them back to the codecs. I don't think we need the actual endpoints anymore though. If we do, we can just have them always return an error about not being implemented anymore.
