### ISSUE TITLE
Investigate synchronized missed blocks.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1569]
## Summary of Bug

According to [ping.pub](https://ping.pub/provenance/uptime) (the click on "blocks"), there are blocks that several validators will simultaneously miss.

<img width="914" alt="Screenshot 2023-05-31 at 12 56 13" src="https://github.com/provenance-io/provenance/assets/6164208/34068192-9b2a-4d21-a9cf-e9d0d6451fa0">

In that image, you can see that several validators have red squares for the same blocks. The right-most synchronized miss is 11282380 and the image also indicates an issue with 11282370, and 11282360.

The block info query (e.g. `provenanced q block 11282381`) has a `.block.last_commit.signatures` section that indicates which validators signed off on the previous block.

We need to get a better picture of these synchronized missed blocks and try to identify why they might be happening.

1. Put something together that will identify synchronized missed blocks and the validators involved with each.
2. Identify validators often involved, sometimes involved, and never involved in these misses.
3. Identify the proposers of these misses to see if there's a pattern.
4. Investigate some of the identified blocks to see if there are any similarities.
5. Identify next steps for either further investigation or fixes.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Here are some notes I have so far.

* `provenanced q block n` -> `.block.header.proposer_address` gives the block proposer.
* `provenanced q block n+1` -> `.block.last_commit.signatures` gives the validator signature info for that block. The addresses here seem to be hex strings of the address bytes.
* `provenanced q tendermint-validator-set` contains bech32 address strings for the validators with HRP `pbvalcons` (e.g. `pbvalcons1ryz97ullxwphrtdvkfm7m88havn6scvumdf227`).
* `provenanced q staking validators` contains more info on the validators (e.g. descriptions), and has bech32 address strings for the validators with HRP `pbvaloper` (e.g. `pbvaloper1hxd75vuud3gddkfpglkzzsvpjwrz9zf05xu4ss`).

I wrote https://github.com/SpicyLemon/SpicyLemon/tree/master/go_fun/bech32 to be to convert hex/base64/bech32 strings and will hopefully be useful for associating the `q staking validators` info with `q block` last block signatures.

I've no idea if the last block signature hex bytes, `pbvalcons` addresses and `pbvaloper` are at all associated though.

**Comment by iramiller** [comment]
Additional information from `Galadrin | Crostnest` (via discord)
![image](https://github.com/provenance-io/provenance/assets/72319/4115f1c1-f388-4a1c-a0c1-3cd0b8685696)

![image-1](https://github.com/provenance-io/provenance/assets/72319/75a9b202-c108-4805-a0c7-23c33cd138d9)

and a near by staking/redelegation to this point in time:
https://www.mintscan.io/provenance/txs/06077C568D9F4A9289B3465DCB59072E2432467090E62B4E5513AE5F03428342?height=11319332

**Comment by SpicyLemon** [comment]
@iramiller and I had a discussion. Here are some takeaways.

* The `consensus.timeout_commit` is the amount of time a node will wait for votes to come in for the last block.
* Having a larger number there can slow down block creation because the node won't move on from block `n+1` until it's waited long enough to get all the votes it can for block `n`.
* Having a lower number allows for faster block creation but the votes from slower nodes might often get missed when not needed for consensus.
* It is possible for two nodes to return slightly different vote results. All the votes needed for consensus would be the same, but nodes in the other 1/3 may or may not be included e.g. in a `query block <n+1>` result depending on the node.

Considering all that, we think a `consensus.timeout_commit` of `1500ms` is probably a better Provenance Blockchain default than `5s`.

#1594 added a `pre-upgrade` command that bumps the setting to `5s` for nodes with it lower than `2500ms`. Now, though, we're thinking we should have it change everyone's to `1500ms`.

**Comment by SpicyLemon** [comment]
From `Jarnek | Panthea EU` in discord:

I may have found another clue regarding all the missed blocks on the chain. It seems that the binary is using alot of disk IO, like.... ALOT compared to other chains.
I checked with this command:
```
lsof | awk '{print $1}' | sort | uniq -c | sort -r -n | head
```
and currently provenanced is having more than 25000 open files. The chain that is closest (of those i validate on) is Bitsong with about 8000 open files.
Maybe you guys can look into this? All that disk IO is a heavy load on many servers and could possibly explain that most validators are missing blocks.
Let me know what you think about this theory, and have a super duper day. 🙂

**Comment by SpicyLemon** [comment]
When I run a `mainnet` or `testnet` node locally (on my Mac), I always run `ulimit -n 10240` first because it wants so many open files.

Just now, though, I fired up an older `mainnet` node still on v1.16 that started with a HighStakes quicksync. As it's catching up, it's sitting around 250 open `provenanc` files. I'll want to see what happens to that in v1.17 and also once it's caught up and running normally. We'll also want to try this with a full quicksync to see what kind of difference that makes.

**Comment by iramiller** [comment]
Another major culprit here is the pruning function ... pruning at certain block heights takes a bunch of time which blocks the node can can cause it to miss blocks ... People like to use the same number (100, 1000, 10000, etc) for these heights which would make them all hit at the same time.
