### ISSUE TITLE
Go build version enforcement

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#1575]
## Summary of Bug

Currently the Makefile only enforces a minimum golang version while a range of versions should be supported.

## Version

HEAD

## Steps to Reproduce

Note that the code enforces a minimum version of go of 1.17 which is incorrect now that 1.20.x is required.  Further given potential incompatibility with future Go versions a tested/supported range of allowed versions should be enforced.

## Remediation

Replace the `validate-go-version` check stuff with something more simple that enforces a range correctly.
```
check-go-version:
	@if ! go version | grep -Eq "go1.20.[1-4]"; then \
		echo "\033[0;31mERROR:\033[0m Go version 1.20.1 through 1.20.4 is required for compiling provenanced. Installed version:" "$(shell go version)"; 

	fi
```
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
I feel like we should allow any patch version unless we have a specific reason that it shouldn't be used.

I can see a little benefit in limiting the major/minor version, and we probably should have done that when 1.18 was required. But the 1.18 requirement was hopefully a one-off. It was the result of a simultaneous change by golang (in v1.19) and a change in the SDK. The SDK says its best for all executables for a chain to be built using the same version of go. But that suggestion is a result of the aforementioned issue. There's no know incompatibilities between go 1.19 and 1.20.

But requiring a specific version is the safe-side of things to do.

For that check, if we want to pay attention to the patch version, I feel like it should be a blacklist. Any time we add to the blacklist, we'd want a comment about why it's not allowed and possibly a custom error message saying why too. But I'm not sure how often we'd get around to updating that blacklist.

I do like the idea of simplifying that check though. Part of the reason it got missed both when we bumped to 1.18 and later to 1.20 is that the strings `1.17`, `1.18`, and `1.20` don't appear anywhere near the check. So when digging through the repo looking for places to update the go version, that check is easy to miss.

**Comment by iramiller** [comment]
I am ok with not worrying about the patch version personally… it just seemed like an easy range check we could do. 

I also feel like the existing version is complex because we can and not because it was required and therefore should be streamlined. Less code is universally better in nearly every case.

**Comment by SpicyLemon** [comment]
#1579 updated the make target to require go 1.20 specifically, but it doesn't pay attention to patch versions.

**Comment by SpicyLemon** [comment]
My hesitation on the patch version is that it could easily cause problems for new users that grab our repo, install go, and try to compile.

Also, we're usually not too on-the-ball when it comes to testing new go versions, specially down to the patch version. So I picture the list of valid patch versions almost always being out-of-date.

**Comment by SpicyLemon** [comment]
I'm going to close this as done in #1579. That requires 1.20 specifically (e.g. neither 1.19 nor 1.21 will work), but allows any 1.20.x patch version. We can reopen this later if we decide to restrict in patch version too.
