### ISSUE TITLE
Include the provenanced version in the node status result.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1578]
## Summary

When getting a node's status (e.g. `provenanced status`), have it include the version of `provenanced` that the node is running.

## Problem Definition

As a provenance blochain code maintainer, I want to be able to find out what version of `provenanced` a node is running so that I can know how much of the network has switched to new versions and also who hasn't.

## Proposal

Somehow, update the node status results to include the provenanced version.

Here's an example of current output (note, this is pointing to a local `mainnet` node).

```
$ provenanced status | jq '.'
{
  "NodeInfo": {
    "protocol_version": {
      "p2p": "8",
      "block": "11",
      "app": "0"
    },
    "id": "aabdf2fd048b1b13f36d8bb83a40fea68bdbf2ed",
    "listen_addr": "tcp://0.0.0.0:26656",
    "network": "pio-mainnet-1",
    "version": "v0.34.26",
    "channels": "40202122233038606100",
    "moniker": "dwedul-mainnet-1",
    "other": {
      "tx_index": "off",
      "rpc_address": "tcp://0.0.0.0:26657"
    }
  },
  "SyncInfo": {
    "latest_block_hash": "5C258B36A59629F16BFB8E8BEA15CC4EBB34ED2748385197A2E37612F48E035D",
    "latest_app_hash": "A56DB754A8851B71C30EE9825FAD5B5000E16E8CEE7B8BFA1E60835E0B76B0A5",
    "latest_block_height": "11406756",
    "latest_block_time": "2023-06-08T18:33:58.995226349Z",
    "earliest_block_hash": "19D1069F9BE699A5E7496066EB00B787D897462137131F80FEBE36D3FFA4796B",
    "earliest_app_hash": "60A60DB6E813C9BE24FEAC027B48D12862377C2FA48FF2AB101FAD15BE4F39CC",
    "earliest_block_height": "11382501",
    "earliest_block_time": "2023-06-07T02:22:07.649361271Z",
    "catching_up": false
  },
  "ValidatorInfo": {
    "Address": "961871B3543F1BD30C9694219B5BDFC396AEBB43",
    "PubKey": {
      "type": "tendermint/PubKeyEd25519",
      "value": "+ca8zZTXmV8kQyhPVUovKtDebpLfjEDDysC+ikoeRwo="
    },
    "VotingPower": "0"
  }
}
```

The `NodeInfo.version` is the version of tendermint/cometbft. It's probably easiest to somehow change that value to the `provenanced` version. But if that's not possible, maybe there's a way to inject our own new field in that result.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Taztingo** [comment]
The `version` query reads the Version variable that is set during the binary's build process, and this info is not sent to tendermint when setting up the node. I think the two options that we have are modifying tendermint to receive that, or making this an actual query that is sent to a node. If we make it an actual query, then this might not be the correct place to add it since it looks like `status` is mainly tendermint oriented.

Also, I noticed that the status command has `latest_block_height"`. Can that be used if the main purpose is trying to figure out if a node switched?

**Comment by SpicyLemon** [comment]
We were only able to add it to the `provenanced status` command (not any of the endpoints) without forking the cometbft/tendermint repo.

So `proveanced status` will now contain a `binary_version` field, but that field won't show up from the `status` endpoint (e.g. `https://rpc.provenance.io:443/status`). However, we already have our own `sync_info` rpc endpoint with a `version` field containing the same binary version value.

```
$ curl -s https://rpc.provenance.io:443/sync_info | jq '.'
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_height": "12006447",
    "block_hash": "F1AB8F2A3CAFCD06E4462A542E706531C1F8B54D3C0F85874889C994629AE8DF",
    "version": "v1.16.0"
  }
}
```

At some point, we might try to hijack that route to return our own custom info (i.e. redefine the `status` entry in the `tmrpccore.Routes` map, kind of how we add that `sync_info` route in `internal/statesync/statesync.go`). But that can left for another day.
