### ISSUE TITLE
Fix testnet statesync

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1617]
## Summary of Bug

Cannot start a `pio-testnet-1` node using statesync.

## Steps to Reproduce

Attempt to start a node using statesync. [ping.pub](https://ping.pub/provenance/statesync) has some good instructions, but they're for mainnet.

for `rpc_servers`:
You can try `https://rpc.test.provenance.io:443,https://rpc.test.provenance.io:443`, but I seem to remember that not working due to dns setup of that subdomain. Last time I tried, I used the old `persistent_peers` ips on port 26657. Basically, choose two of these: `35.232.121.26:26656` `35.194.76.143:26656` `34.75.172.89:26656` `34.82.40.187:26656`. I know I tried all combos of two of those, and couldn't get it to start up.

## Symptoms

1. It grabs very old blocks.
2. It fails to validate them and just gets stuck, possibly since they're so old, possibly the other nodes have different config settings.

Last time I had a op look on the testnet nodes, the `data/snapshots/` dirs all had different things and might not have been cleaning itself up. Will probably need to coordinate some cleanup/changes with them.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Note that https://github.com/CosmWasm/wasmd/tree/v0.41.0 has a reference to accepting data for state sync.  This may be required to make this work.
