### ISSUE TITLE
Accepting Quarantined Restricted Marker Errors

### ISSUE THREAD

**Issue by tbrooks-figure** [provenance-io/provenance#1626]
## Summary of Bug

When a restricted marker gets quarantined due to the recipient having opted in, the restricted marker cannot be accepted unless the restricted marker grants transfer auth to the quarantine module.

## Version

v1.16.0

## Steps to Reproduce
1. Create a restricted marker
2. Set up a wallet and opt in to quarantine
3. Send some of the restricted marker coin to the quarantined address
4. Attempt to accept the quarantined funds. Ex: 
```
provenanced tx quarantine accept quarantine-tt4 tp1j82e50f7qp5slv8fu9ymffapf7vxhtsr5xcka6 -t --node http://localhost:26657 --chain-id testing --gas auto --gas-prices 1905nhash --gas-adjustment 1.3
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: tp1cttxw40x6z6z77j5rp7qyr6vsrmhjcs2czz9lg does not have transfer permissions [provenance-io/provenance/vendor/github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:859] With gas wanted: '18446744073709551615' and gas used: '59673' : unknown request
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
It make sense to me to have some hard-coded whitelist addresses for the marker module. These addresses wouldn't be required to have the required attributes, and wouldn't be required to have transfer authority. We'd want to do some analysis on all the aspects of the marker send restriction to figure out which can be bypassed here. As part of that analysis, we should consider pros/cons of applying the marker module's `SendRestrictionFn` before/after the quarantine module's.

The addresses we'd want to whitelist are the quarantine module, fee collector, reward keeper, and maybe the bonded and not-bonded pools. The bonded and not-bonded pools can only ever hold the bond denom. So for mainnet, those wouldn't need to be whitelisted, but if a private zone wanted to use a restricted token as the bond denom, we'd want them whitelisted too.
