### ISSUE TITLE
Upgrade ibc-go to v8.0.0

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/provenance#1707]
## Summary

Upgrade ibc-go dependency to v8.0.0 when that is released.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
This was done as part of our `v0.50.x` updates and is part of `v1.19.0`.
