### ISSUE TITLE
Update relayer to support IBC v8.0.0

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1716]
## Summary

The relayer that we use for the ibc network will need to be updated to support IBC v8.0.0

## Problem Definition

The go relayer team announced that they were making changes to the relayer to support the latest version of IBC v8.0.0. We should update to ensure we support all the latest features.

## Proposal

Update the relayer version in the docker file once it has been released.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
The IBC stuff was all bumped to `v8.x` for `v1.19.0-rc2`.
