### ISSUE TITLE
Missing logging in Trigger module

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1718]
## Summary

Add additional logging to the trigger module.

## Problem Definition

There is not much logging in the trigger module, and it will be difficult for us to trace when an error does arise.

## Proposal

Add additional logging to the detection, loading, and firing phases of the trigger module.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
We probably want to log at trace/debug level for trigger set actions and trigger execution... the trigger id and matched event should be enough on the set side ... trigger id and the result (ok/error) on the execution
