### ISSUE TITLE
Provenance Blockchain 1.17.0 Testing

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1719]
# Summary

Release v1.17.0 of the Provenance Blockchain needs local and testnet testing before being pushed to the mainnet.

## Testing / Verification Areas

Please assign yourself to an issue and update the test column with the appropriate symbol after testing. Tests are not limited to 1 person, and it's encouraged to test the work of others 😃.

| Icon | Meaning | Code |
| --- | --- | --- |
| :white_large_square: | Not tested | :white_large_square |
| :white_check_mark: | Tested and passed | :white_check_mark |
| :x: | Tested and failed | :x |

`v1.17.0-rc2`

| Issue | Tester(s) | Local Test | Testnet Test | Notes |
| --- | --- | --- | --- | --- |
| Upgrade Handler saffron-rc2  | @Taztingo | :white_check_mark: | :white_check_mark: |  |
| Exchange Module  | @SpicyLemon  | :white_large_square: | :white_large_square: | Found a couple queries that don't quite work right. |
| Prevent transfer of restricted coin with deny list on send.  |   | :white_large_square: | :white_large_square: |  |
| Marker Net Asset Value  |   | :white_large_square: | :white_large_square: |  |
| Oracle Module  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| Metadata GetByAddr  |   | :white_large_square: | :white_large_square: |  |
| HoldModule  |   | :white_large_square: | :white_large_square: |  |
| Marker Max Supply Param  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| Docgen command  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| ICS-20 Marker Creation  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| IBC Marker Denom Metadata | @Taztingo | :white_check_mark: | :white_check_mark: | ibc metadata descriptions have been updated to include the chain id. |

**Comment by SpicyLemon** [comment]
Updating the main issue summary to reflect `saffron-rc2`. Here's what it used to have:

`v1.17.0-rc1`

| Issue | Tester(s) | Local Test | Testnet Test | Notes |
| --- | --- | --- | --- | --- |
| Upgrade Handler saffron-rc1  | @dwedul-figure   | :white_check_mark: | :white_check_mark: |  |
| Exchange Module  | @SpicyLemon  | :white_large_square: | :x: | Found a couple queries that don't quite work right. |
| Prevent transfer of restricted coin with deny list on send.  |   | :white_large_square: | :white_large_square: |  |
| Marker Net Asset Value  |   | :white_large_square: | :white_large_square: |  |
| Oracle Module  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| GetByAddr  |   | :white_large_square: | :white_large_square: |  |
| HoldModule  |   | :white_large_square: | :white_large_square: |  |
| Marker Max Supply Param  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| Docgen command  | @Taztingo   | :white_check_mark: | :white_check_mark: |  |
| ICS-20 Marker Creation  |   | :white_large_square: | :white_large_square: |  |
