### ISSUE TITLE
Support setting a NAV attribute on metadata scopes 

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#1749]
## Summary

Add the ability to set a NAV on a given scope to indicate its value for TVL

## Problem Definition

With the release of 1.17 markers now have a new TVL component that allows users to set information about the prices/value of a given token.  Expanding on this capability we need to add a similar value to the metadata/scopes so that it is easy to declare a given value of an asset when it is created (USD).

## Proposal

Add an attribute to the scope concept (doesn't have to be directly in the scope proto) which allows a user to assign a USD NAV value similar to the one set for markers.  Unlike the markers there will not be an exchange function that updates these values until perhaps at a future date the exchange system is expanded to allow trading of scopes directly (instead of requiring them to be tied to a marker).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Are the scope NAVs only supposed to be in USD?  Marker module supports multiple NAVs of different denoms.  If we want to do that here, I would suggest not having a proto directly on the scope.

**Comment by iramiller** [comment]
To start with I don't know that we will need the alternate pricing ... but that is certainly coming, if not in the first revision then in a subsequent one.
