### ISSUE TITLE
Exchange Commitment Hold

### ISSUE THREAD

**Issue by jdfigure** [provenance-io/provenance#1789]
## Summary

Participation in an exchange often requires investors to commit capital to the exchange as "buying power". This capital is transferred to the exchange operator where the exchange operator holds the capital and then allows the investor to participate in their exchange with buying power up to the capital commitment amount.

This request is to build "capital commitment hold" functions in the Provenance Blockchain exchange module that allows investors to commit buying power to an exchange operator. This has many advantages:
* Any on-chain asset can be committed as buying power to an exchange operator
* Assets committed to an exchange provide excellent on-chain transparency - thus the viability, vitality, and size of an exchange are instantly available on-chain.
* Investors don't lose sight of their assets - assets committed to an exchange still show in the investors wallet account balances but are "non-spendable"
* Exchanges can efficiently settle held assets between accounts based on high-frequency or batched off-chain activity (i.e. order books).
 
## Problem Definition

What problems may be addressed by introducing this feature?

The ability to commit capital and have it managed by an operator has historically been done with smart contracts. Having this functionality in the protocol provides a safer, more scalable approach.

What benefits does the Provenance Network stand to gain by including this feature?

Increased transactions, increased TVL, increased fees, and a novel on-chain settlement for off-chain order book exchanges.

Should this feature be implemented in the Cosmos SDK directly?  No, Provenance is a better ecosystem for this financial services-specific feature.

Are there any disadvantages of including this feature? Not to the protocol. Exchange operators will need to consider gas fees paid during settlement, releasing, and locking.

## Proposal

Enhance the Provenance exchange module to:
* Allow investors to commit assets to an exchange operator where:
  * Assets are still visible to the investor after transfer (i.e. doesn't affect their balance of the asset)
  * Assets committed to an exchange operator are un-spendable
  * Investors can request release of all or a portion of the committed value requiring approval from the exchange operator
  * Commitments are assigned and return a unique, queryable identifier
* Allow exchange operators to:
  * Rebalance commitments
    * For example, Alice commits 10hotdog to the exchange. Alice trades, in the off-chain order book, 3hotdog to Bob. The exchange settles at some interval and requests a transfer of 3hotdog from Alice to Bob. Alice now has 7hotdog committed to the exchange and Bob has 3hotdog committed to the exchange.
    * Rebalancing should provide batching features to reduce cost and processing
  * Release commitments where a release makes the committed asset spendable to the current holder and removes it from the exchange operator hold
     * Release by committer address
     * Release by commitment ID
* Query by exchange operators, committer address, commitment ID
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jtalis** [comment]
Another consideration for this proposal is a need to create an authz grant for a commitment up to some max amount. If a user is depositing funds to their account, this would allow them to indicate to the exchange operator that they want to commit those funds once they hit their account.

**Comment by jtalis** [comment]
> 
> I don't see where an AuthZ grant factors into this. Are you expecting to grant someone else the ability to create commitments on your account? Or are you expecting to grant someone else authority on the market API to propose settlement instructions?

The use case is that someone wants to commit funds to the exchange, but those funds have not hit their account yet. In a single step from a UX standpoint, they could initiate a deposit to their account and instruct the exchange operator to commit those funds once they arrive

**Comment by iramiller** [comment]
Related to this issue... from a discussion with @jdfigure this morning we want to make sure that the market operator has a flexible ability to manage/release portions of the commitment.  This would be used during withdraws so release some or all of the committed funds.
