### ISSUE TITLE
Update nav protos and documentation to use millis

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1813]
## Summary

We are in the process of updating our navs to use millis, and we should also update the protos + cli portion to use them.

## Problem Definition

This is needed for the other work we are doing on the backend for millis.

## Proposal

1. Update protos
2. Update cli
3. Update documentation
4. Think about USDDenom if it should be either "usd" or "usdmilli"

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Oddly enough it isn't the SI prefix milli it is the official currency denomination of [mill](https://en.wikipedia.org/wiki/Mill_(currency)). So in this case we would be using the term `usdmill` just like `usdcent`, etc...
