### ISSUE TITLE
Unable to marker transfer from a group account

### ISSUE THREAD

**Issue by jtalis** [provenance-io/provenance#1818]
## Summary of Bug

When a marker has `allow_forced_transfer` set to true, a marker transfer from a group account fails for an account with `MARKER_TRANSFER` permission even through an authz grant exists

## Version

1.17.1

## Steps to Reproduce

1. Create a restricted marker with `allow_forced_transfer = true` and withdraw some coin to a group account.
2. Create an authz grant for the group account to allow transfer of the marker by an account with `MARKER_TRANSFER` permissions
3. Signing with the account with marker transfer permissions, attempt to transfer the coin from the group account.
4. Note the error `funds are not allowed to be removed from {group address}`

example failure:

https://explorer.test.provenance.io/tx/3740C759C9A3117E84E4B6B9B9273B2AE351CC0DEC7CC54191DDD50B8C90D454/19980649

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by vwagner** [comment]
Just a comment that this transaction is slightly odd in that the smart contract (the `grantee` of the transfer authority authz grant) already had `TRANSFER` authority on the Marker. In other words, the authz grant here was likely unnecessary.
