### ISSUE TITLE
Dependabot changed labels, broke changelog

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#1869]
## Summary of Bug

The updated dependabot no longer labels PRs with ‘dependabot’ it uses ‘dependacies’ which has broken our change log workflow. 

## Version

main

## Steps to Reproduce

Review any PR from dependabot, note the changelog job doesn’t see the required label and so it doesn’t run despite the successful execution. 
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
We got this fixed at some point in the last month. :D
