### ISSUE TITLE
Record net value asset only when explicitly set by user when adding marker

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/provenance#2030]
## Summary

Determine if the net asset value needs to be written as a record when adding a marker, based on whether it was explicitly set by the user.

## Problem Definition

Currently, the net asset value is being written on an add marker transaction even if it hasn't been set by the user. This can cause confusion as it is unclear whether the value was intentionally left unset by the user or if they are using an older proto version that does not include these fields.

## Proposal

Implement a mechanism to check if the `volume` and `usd_mills` fields have been explicitly set by the user before writing them as a record in the add marker transaction. This could involve:

1. Checking for default values and determining if the fields are explicitly set.
2. Using wrapper types to better handle the presence or absence of these fields.
3. Adding version checks or flags to differentiate between different proto versions.

This enhancement will help prevent confusion and ensure that only intended values are recorded.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Probably work on this at the same time as #2029
