### ISSUE TITLE
SIGSEGV on startup connecting to testnet

### ISSUE THREAD

**Issue by settonull** [provenance-io/provenance#2041]
## Summary of Bug

I have just cloned and built provenanced and am attempting to join the testnet network.  On start I get a SIGSEGV crash.  I'm not sure if this is the correct place to report but wasn't sure where else.  I scanned the existing issues and didn't see anything.  Don't know go so not sure where to start in debugging, hopefully it is just something embarrassingly wrong in my setup.  

Here is the full error

$ provenanced start --testnet --p2p.seeds 4403e0e55fa4e43a454c4bf7922c8a93a51fb12d@seed.test.provenance.io:26656
8:19PM INF starting node with ABCI Tendermint in-process
8:19PM INF service start impl=multiAppConn module=proxy msg={}
8:19PM INF service start connection=query impl=localClient module=abci-client msg={}
8:19PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
8:19PM INF service start connection=mempool impl=localClient module=abci-client msg={}
8:19PM INF service start connection=consensus impl=localClient module=abci-client msg={}
8:19PM INF service start impl=EventBus module=events msg={}
8:19PM INF service start impl=PubSub module=pubsub msg={}
8:19PM INF service start impl=IndexerService module=txindex msg={}
8:19PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v1.16.0
8:19PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
8:19PM INF initializing blockchain state from genesis.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1400fe9]

goroutine 36 [running]:
math/big.(*Int).Sign(...)
        math/big/int.go:49
github.com/cosmos/cosmos-sdk/types.Dec.IsNegative(...)
        github.com/cosmos/cosmos-sdk@v0.46.10/types/decimal.go:211
github.com/cosmos/cosmos-sdk/x/staking/types.validateMinCommissionRate({0x27f2ec0?, 0x0?})
        github.com/cosmos/cosmos-sdk@v0.46.10/x/staking/types/params.go:226 +0x49
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x35fa660, 0xc00115fad0}, 0xc0013c8228, {0x35c3760, 0xc00138f6b0}, {0x35c3800, 0xc00138f800}, {0xc0014ab008, 0x7, 0x18}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.10/x/params/types/subspace.go:262 +0x1c4
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.SetParams(...)
        github.com/cosmos/cosmos-sdk@v0.46.10/x/staking/keeper/params.go:71
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.InitGenesis({{0x35c3760, 0xc00138f660}, {0x35fa660, 0xc00115fad0}, {0x35e7d40, 0xc001375720}, {0x7f7c841cd648, 0xc001388900}, {0x35f8fc8, 0xc00128a150}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.10/x/staking/keeper/genesis.go:28 +0x1aa
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{0x36019a0, 0xc00115fad0}}, {{0x35c3760, 0xc00138f660}, {0x35fa660, 0xc00115fad0}, {0x35e7d40, 0xc001375720}, {0x7f7c841cd648, 0xc001388900}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.10/x/staking/module.go:152 +0x105
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x35e3c98, 0x4cbc5c0}, {0x35fa890, 0xc00058a200}, {{0x0, 0x0}, {0xc00161a220, 0xd}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.10/types/module/module.go:322 +0x33f
github.com/provenance-io/provenance/app.(*App).InitChainer(_, {{0x35e3c98, 0x4cbc5c0}, {0x35fa890, 0xc00058a200}, {{0x0, 0x0}, {0xc00161a220, 0xd}, 0x0, ...}, ...}, ...)
        github.com/provenance-io/provenance/app/app.go:938 +0x1c5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0012c9a40, {{0x918e34e, 0xed7d9b942, 0x0}, {0xc00161a220, 0xd}, 0xc0006e18a0, {0x4cbc5c0, 0x0, 0x0}, ...})
        github.com/cosmos/cosmos-sdk@v0.46.10/baseapp/abci.go:73 +0x3f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000693320, {{0x918e34e, 0xed7d9b942, 0x0}, {0xc00161a220, 0xd}, 0xc0006e18a0, {0x4cbc5c0, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.28/abci/client/local_client.go:272 +0x102
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x918e34e, 0xed7d9b942, 0x0}, {0xc00161a220, 0xd}, 0xc0006e18a0, {0x4cbc5c0, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.28/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2814b6e, 0x7}}, {0xc00161a220, 0xd}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.28/consensus/replay.go:319 +0xe78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000f47d78, {0x35fd5d0, 0xc0013ba000})
        github.com/tendermint/tendermint@v0.34.28/consensus/replay.go:268 +0x374
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2814b6e, 0x7}}, {0xc00161a220, 0xd}, 0x1, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.28/node/node.go:329 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc001848280, {0x35c6c88, 0xc0016bcb40}, 0xc001434cf0, {0x35b8c20, 0xc0001812f0}, 0xc000f499c0, 0x2fb3e40, 0xc000f499b0, {0x35e3c60, ...}, ...)
        github.com/tendermint/tendermint@v0.34.28/node/node.go:779 +0x557
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x360d768, 0xc00178bda0}, 0x0, {0xc0016c0020, 0xd}, {0x36019a0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.10/server/start.go:301 +0x7a5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
        github.com/cosmos/cosmos-sdk@v0.46.10/server/start.go:147 +0x45
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
        github.com/cosmos/cosmos-sdk@v0.46.10/server/start.go:537 +0x23
created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile in goroutine 1
        github.com/cosmos/cosmos-sdk@v0.46.10/server/start.go:536 +0x23f

## Version

$ provenanced version
v1.16.0

## Steps to Reproduce

I follower the quickstart guide from - https://developer.provenance.io/docs/pb/blockchain/running-a-node/running-a-node-1/join-provenance-testnet/

full history of commands from a clean AWS start - 

sudo yum install make golang docker
export PATH=$PATH:\~/go/bin
export PIO_HOME=\~/.provenanced
git clone https://github.com/provenance-io/provenance.git
cd provenance
git checkout tags/v1.16.0 -b v1.16.0
make clean
make install
curl https://raw.githubusercontent.com/provenance-io/testnet/main/pio-testnet-1/genesis.json > genesis.json
mv genesis.json $PIO_HOME/config
provenanced start --testnet --p2p.seeds 4403e0e55fa4e43a454c4bf7922c8a93a51fb12d@seed.test.provenance.io:26656 --x-crisis-skip-assert-invariants

I also tried replacing the seeds with those from https://github.com/provenance-io/testnet/tree/main/pio-testnet-1 with the same result.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
You can not use the latest version of the software to sync from genesis (which is what this appears to be doing since it is starting with block height 0.  You would need to use a quick sync or state sync copy of the blockchain then continue from there.

If you do want a full copy of testnet from genesis then you would need to sync the last several years of blocks through upgrading from the original version of the software used and all the subsequent upgrade versions.  There are a lot of upgrades to do though https://explorer.test.provenance.io/network/upgrades

**Comment by iramiller** [comment]
You can download a quick sync copy of the data to get your node started right away on the v1.18.0 (latest) version of the software using the associated backup from https://test.provenance.io/quicksync

**Comment by settonull** [comment]
Got it, yeah don't need to go from genesis, I'll grab the latest quicksync and upgrade to 1.18.0-rc3.  Thanks for your quick help!
