### ISSUE TITLE
Update swagger documentation

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#2063]
## Summary

Current swagger documentation could use some additional refinement and grouping of methods along with general dependency updates

## Problem Definition

The current swagger listing puts all endpoints in one very large list without any categories.  In addition it relies on the out of date statik build/resource flow instead of the native go embed approach.

## Proposal

- Update the swagger/openapi build flow with additional documentation, descriptions, and method tag organization.  
- Move to the go embed flow from the existing statik compiled resource approach.  
- Update to current versions of the swagger bundled css/javascript

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Issue #404 looks like a copy of this one, so I'm closing that one. It linked to a related SDK issue as a reference, and also an article about swagger 2 vs openapi 3: https://medium.com/@tgtshanika/open-api-3-0-vs-swagger-2-0-94a80f121022
