### ISSUE TITLE
Use the bank module to track the value owners of scopes.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#2137]
## Summary

Use the bank module to keep track of the value owner of a scope.

## Problem Definition

Scopes have to be read and written in order to update the value owners which causes a lot of unneeded read/writes. There are several operations that only update the value owner, though, that could be made much cheaper by extracting the value owner into its own record. Further, things like quarantine and sanction should apply to scope value owners too.

## Proposal

Use the bank module to record the value owner of scopes by giving each the denom "nft/<scope id>", e.g. `nft/scope1qzge0zaztu65tx5x5llv5xc9ztsqxlkwel`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
> Drawbacks:
> 
> - More complex metadata module since it'll now be using/managing bank state too.

This would be a reason to not convert existing endpoints to their bank managed counter parts... I guess that still doesn't let us simplify this away though because creating a scope means minting the token with the bank module as well...
