### ISSUE TITLE
Create unit-test for parse public key and assert correct behavior

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#225]
## Summary of Bug

Parse public key appears to incorrectly handle public keys (observed behavior: empty addresses) when used by memorialize contract

## Version

v1.0.0-HEAD

## Steps to Reproduce/Remediation

During testing of P8e client integration using Memorialize contract it seems that the parse public key method is not behaving as expected.  Create a unit-test for this method and ensure it correctly handles both 33 byte (compressed) and 64 byte (uncompressed) secp256k1 keys.

https://github.com/provenance-io/provenance/blob/4192fd46ea56574bb4ffcacb632d8bb54a720b28/x/metadata/types/p8e.go#L381-L391

Appropriate test case public key values:

```go
// TODO @piercetrey-figure will supply these test case values
comp := ''"
uncomp := ""
```
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by piercetrey-figure** [comment]
here are the uncompressed/compressed base64-encoded forms of a secp256k1 public key

uncompressed: `BGxX6eJRAdXlU64APi95Al44m1FJVgfHlrTpXAqUAB+8JNhM0HgIGWElKbgD6K0KOX9HTJZdlX0z3WTmQrdW+8Q`
compressed: `AmxX6eJRAdXlU64APi95Al44m1FJVgfHlrTpXAqUAB+8`
