### ISSUE TITLE
Denom Metadata: Require unique denom strings and delimiter after SI prefix.

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#248]
## Summary

A denom string must uniquely identify a marker. If a denom string ambiguously refers to two or more markers, then we don't actually know the coin in question.

## Problem Definition

Current restrictions require a denom unit name or alias to be either the root coin name, or an SI Prefix + the root coin name. This will cause a collision in some cases when new markers are being created. For example, if an existing marker has a root coin name of `oocoin`, it might have a denom unit for `foocoin` (being one "femto oocoin"). Then a new coin comes along named "foocoin". We create the marker for it including a denom unit for the root coin name "foocoin". Now, if someone is trying to do a transaction with "1000 foocoin", we don't know which one they're talking about.

## Proposal

- [ ] Require either a `-` or `.` between the SI prefix and root coin name of all denom unit names and aliases. Since the base name and display name must both be denom units, this applies to those as well (for free).
- [ ] Update `GetRootCoinName` to remove any leading `-` or `.` (for cases when the root coin name isn't in a denom unit entry).
- [ ] None of the denom unit names or aliases can start with a `-` or `.`.
- [ ] Restrict denom names and aliases to 63 characters long (including any prefix and delimiter).
- [ ] Require all denom unit names and aliases to be unique across the chain.
    - [ ] Create an index for all denom unit names and aliases in the kvstore.
        - [ ] The key should have this format: `<key byte><denom name><delimiter byte><base name>`
            - [ ] The <key byte> should just be a single byte that uniquely identifies the index entries.
            - [ ] The <denom name> should be the name as bytes.
            - [ ] The <delimiter byte> can be anything as long as it's not possible in a denom name. Maybe just reuse the <key byte> here.
            - [ ] The <base name> should be the base name as bytes (the same base name used in the kvstore key for the marker).
        - [ ] The value should just be `0x01`.
        - [ ] Index entries should be made for all denom `metadata.Denom` strings, and all `metadata.Aliases` entry strings.
        - [ ] Create an iterator for the index that takes in a prefix to iterate over, breaks each key into the denom and base name, and calls a function with the denom and base name as parameters.
    - [ ] During `ValidateDenomMetadataExtended` check the index for existing entries for each denom name and alias that refer to different denom base names.
- [ ] Update `DenomMetadata` query to use the new index for looking up the denom metadata by denom string.

## Reasoning

By requiring a delimiter after the SI prefix, we can ensure that a prefixed denom for an existing coin does not collide with the root coin name of a new coin. E.g. "foocoin" must refer to the root coin name of "foocoin" because there's no delimiter, and "f-oocoin" must be a "femto oocoin". By also not allowing the root coin name to start with a delimiter, there is no room for ambiguity with "f-oocoin".

By indexing all the names an aliases, enforcing uniqueness becomes easy. It also opens up possibilities for more easily finding markers and their associated entries.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Its important that the prefixes support the basic use cases of `nhash`, `uatom`, etc which would mean the base name wouldn’t have a separator from the prefix in these cases...

**Comment by dwedul-figure** [comment]
> Its important that the prefixes support the basic use cases of `nhash`, `uatom`, etc which would mean the base name wouldn’t have a separator from the prefix in these cases...

We absolutely must have unique denom unit names and aliases though. Without the separator, we get ourselves into a sticky situation when a new coin comes out that has a name that is an SI prefix + another coin name. If the existing coin already has the new coin's name as a denom unit name or alias, then the new coin would not be allowed to have its root coin name as a denom unit. It'd only be allowed to have prefix+name entries. And then users wouldn't know (without doing a lookup) which marker the prefixed existing coin refers to.

**Comment by iramiller** [comment]
Indeed that is the part that makes this complex... a separator isn’t going to be a reasonable easy way out here though... given the metadata is optional I would rather prohibit the extra metadata.

**Comment by iramiller** [comment]
Also... @dwedul-figure  you may want to check the assumptions with the regex and matchstring on denom... while anchors are typically required I am positive that the base denom validation expression prevents denim's from starting with a number which a partial match would allow.

**Comment by iramiller** [comment]
>  I am positive that the base denom validation expression prevents denim's from starting with a number which a partial match would allow.

#260 contains the updates to enforce anchors in the marker unrestricted regex the same way the SDK does for coin denom.

**Comment by dwedul-figure** [comment]
I'm going to close this as a "Won't Do" at least for now.

After discussions, it sounds like having a delimiter after the SI prefix is not something that's desired. We still might run into issues regarding uniqueness of names, but hopefully not any time soon.
