### ISSUE TITLE
CLI command to get marker denom metadata

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#249]
## Summary

Create a new CLI command in the marker module that gets denom metadata entries.

## Problem Definition

I'd like to be able to call the `DenomMetadata` query from the command line.

## Proposal

- [ ] Create new marker cli query command with `Use: "metadata [denom]"`, and an alias of `md`.
- [ ] Use the denom provided to call the `DenomMetadata` query endpoint and output its response.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Denom metadata is queried through the bank module cli.
