### ISSUE TITLE
Additional Marker Types

### ISSUE THREAD

**Issue by Gabrinthei** [provenance-io/provenance#250]
## Summary

Need a way to distinguish various marker meta types

## Problem Definition

In the former version of PB the MarkerTypes enum of MarkerAccounts used to be a broader list: 
```
ACCOUNT,
POOL,
FUND,
SECURITIZATION,
COIN,
PARTICIPATION,
SYNDICATION,
STOCK,
OPTION,
WAREHOUSE <-- New
```

Looking at the [new definition of MarkerType](https://github.com/provenance-io/provenance/blob/main/proto/provenance/marker/v1/marker.proto#L61) it appears that has been repurposed. 

## Proposal/Question

Is there an alternative property where these meta types can be set? If not, is this something markers are imagined to support or has that concept been phased out?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
The marker type field was not ever intended for unrestricted use... the type indicates what specific behaviors and logic the marker module should enforce on chain... sounds like you might want to use an attribute or perhaps we need to further explore if there are additional behaviors the module would need to handle which would mean we need to add another type beyond coin/restricted–coin

**Comment by Gabrinthei** [comment]
Ah. Yes, I think attributes will work well. Thanks for pointing me in that direction
