### ISSUE TITLE
Update signing behavior process for marker transfers

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#262]
## Summary of Bug

Marker transfers originally required signatures from both the from account and an account with transfer permission on the marker.  While this approach is correct it does not allow a smart contract to facilitate transfer.

## Version

1.2.0+

## Fix

Update the marker transfer process to utilize the Cosmos SDK 0.43 authz grant module so the from account can set an explicit approval for a transfer to occur from their account.  See #246 for previous discussion

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by channa-figure** [comment]
This is a duplicate issue of #265
