### ISSUE TITLE
Align name module events with marker module convention

### ISSUE THREAD

**Issue by arnabmitra** [provenance-io/provenance#267]
## Summary

Align name module events with marker module convention

## Problem Definition

Would be good to align all modules to produce typed event's from code in a uniform manner, right now name module produces everything from msg_server.go (should be keeper) and also does not include the `EventTypeMessage = "message"` event (i think )

## Proposal

Refactor code to align other modules.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
this ticket should match the existing typed events tickets...
https://github.com/provenance-io/provenance/issues/86

**Comment by arnabmitra** [comment]
> previous work here: #85

we already have typed event's in name module per https://github.com/provenance-io/provenance/issues/85 existing code was in msg_server not in keeper, this ticket should move it to keeper..not sure we need details again on this, but feel free to add it 🤷  or close this issue

**Comment by iramiller** [comment]
I just linked to the previous because I am not sure all the telemetry pieces were added (or if they need to be I guess)
