### ISSUE TITLE
Verify IBC settings

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#272]
## Summary

Verify IBC configuration and settings by creating a channel between testnet-beta and pio-testnet-1 for `vspn` transfer

## Problem Definition

Further testing of the IBC capabilities of the provenance networks is required for mainnet tuning. One of the most useful ways to determine proper configuration is through testing the capabilities between our two current testnets.

## Proposal

- [ ] Launch an appropriate relay and connect `testnet-beta` with `pio-testnet-1`.  
- [ ] Transfer vspn from beta to testnet-1.
- [ ] Test the transfer of various marker coin denoms between networks.
- [ ] Document configuration

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by arnabmitra** [comment]
created provenance chain with ibc config as ```"ibc": {
      "client_genesis": {
        "clients": [],
        "clients_consensus": [],
        "clients_metadata": [],
        "params": {
          "allowed_clients": [
            "06-solomachine",
            "07-tendermint"
          ]
        },
        "create_localhost": false,
        "next_client_sequence": "0"
      },
      "connection_genesis": {
        "connections": [],
        "client_connection_paths": [],
        "next_connection_sequence": "0"
      },
      "channel_genesis": {
        "channels": [],
        "acknowledgements": [],
        "commitments": [],
        "receipts": [],
        "send_sequences": [],
        "recv_sequences": [],
        "ack_sequences": [],
        "next_channel_sequence": "0"
      }
    },``` identical to http://35.232.121.26:26657/genesis? (pio-testnet-1)

created samoleans tokens on provenance chain.. started cosmos chain with gaiad

```
 "ibc": {
      "client_genesis": {
        "clients": [],
        "clients_consensus": [],
        "clients_metadata": [],
        "params": {
          "allowed_clients": [
            "06-solomachine",
            "07-tendermint"
          ]
        },
        "create_localhost": false,
        "next_client_sequence": "0"
      },
      "connection_genesis": {
        "connections": [],
        "client_connection_paths": [],
        "next_connection_sequence": "0"
      },
      "channel_genesis": {
        "channels": [],
        "acknowledgements": [],
        "commitments": [],
        "receipts": [],
        "send_sequences": [],
        "recv_sequences": [],
        "ack_sequences": [],
        "next_channel_sequence": "0"
      }
    },```

Simple transfer of samoleans token works from chain-0 to chain 1..

lot's to understand before using this on production, see https://github.com/informalsystems/ibc-rs/blob/cfbb7663d5bd4767db3646d31f6e7c6258644332/docs/disclosure-log.md with regards to running the relayer in a robust fashion

**Comment by arnabmitra** [comment]
Closing this because initial investigation on ibc config on provenance chain seems to be working, see comment ^^
