### ISSUE TITLE
Update binary release workflow

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#30]
Currently the goreleaser workflow doesn't include any platform binaries for each release.  The release workflow should build a few basic binaries for linux/x64 platforms or potentially official docker images.

**Comment by iramiller** [comment]
Alternatively we could use the `go get` workflow I suspect.  Would need to check with @mlatimer-figure on what the devops crew would prefer.

**Comment by mlatimer-figure** [comment]
> Alternatively we could use the `go get` workflow I suspect. Would need to check with @mlatimer-figure on what the devops crew would prefer.

I think go get would be great for an initial pull or for those that want to upgrade their nodes manually. However we will still need a binary link for those that would like to upgrade their nodes automatically with cosmovisor

**Comment by iramiller** [comment]
We need to add hashes to this process somehow to support cosmovisor upgrades.
