### ISSUE TITLE
Broadcast tx with multiple msgs can randomly error with code 4

### ISSUE THREAD

**Issue by leeduan** [provenance-io/provenance#308]
## Summary of Bug

A transaction broadcast with *multiple* messages can randomly error out with the following signing error:

```
failed with code 4, details: signature verification failed; please verify account number (455) and chain-id (pio-testnet-1): unauthorized
```

This does not seem to happen all the time using the same executable code and signing methodologies. Bumping the gas adjustment multiple relative to estimate by 2X still does not resolve the issue.

This has happened in multiple applications executing different message payloads. Some examples:

* withdraw shares of marker A and mint marker B in the same payload
* Submit multiple execute action wasm messages against a smart contract

## Version

1.2.0

## Steps to Reproduce

```
TxBody.newBuilder().addAllMessages(msgs.map { it.toAny() }).build()
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
In order to reproduce this we need an example of a specific transaction that is submitted which fails.

**Comment by iramiller** [comment]
Provided examples show a signature failure which indicates a client side issue with signing the request.

**Comment by iramiller** [comment]
Issue was determined to be the hashing function used to calculate the signature on the client.
