### ISSUE TITLE
Grpc errors are not mapped to status codes

### ISSUE THREAD

**Issue by leeduan** [provenance-io/provenance#309]
## Summary of Bug

All grpc requests that error out no longer get mapped to a useful response status, instead falling back to code UNKNOWN(2). The statuses use to map better with INVALID_ARGUMENT(3) or NOT_FOUND(5) providing context to the type of error.

Regression makes status handling rely on string parsing which is brittle and prone to error. Robust error handling is currently impossible.

## Version

1.2.0

## Steps to Reproduce

Make any grpc call for a resource that is `not found` but still receives a GrpcStatusRuntimeException with code UNKNOWN

Examples:

```
UNKNOWN: rpc error: code = NotFound desc = account tp12ezhvqud3xjpdz6fp3zj22jgyusurunr3gtch6 not found: key not found
```

```
UNKNOWN: invalid request: invalid marker denom: foobarcoinfoo: decoding bech32 failed: invalid index of 1: invalid request
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by channa-figure** [comment]
Duplicate issue of #326
