### ISSUE TITLE
Bug Report Test from Pippin

### ISSUE THREAD

**Issue by nippip** [provenance-io/provenance#33]
I am wondering who these go to at this point.  
Thanks -- Pippin

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Well... thats going to be who ever is "watching" the repository as a standard github feature.
