### ISSUE TITLE
Allow Value Owner changes without scope owner approvals

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#347]
## Summary

Currently the update scope functionality requires all owner signatures anytime values change in the scope as well as the additional value_owner approvals when these fields change.  An updated flow would allow the value owner to transfer ownership to another value owner address without requiring scope owners to sign

## Problem Definition

The value owner concept on a scope allows a separation between the accounts that maintain a scope/records and those that hold the value of these assets.  While a value owner must approve any change to the value owner field once it is set, there is not currently support for the value owner to update this value independent from the scope owner.  This prevents simple transfer of asset value between accounts, especially when there are many other accounts involved.

## Proposal

Modify the Validate Scope Update code to determine if the only field changing is the "value owner".  When this situation occurs do not add the exisitng scope owners to the required signatures list.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
@Gabrinthei 👀

**Comment by Gabrinthei** [comment]
Looks solid. Thank you!
