### ISSUE TITLE
Verify Rosetta support

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#365]
Cosmos SDK 0.43 adds support for the Rosetta api from Coinbase.  
- [ ] Verify the Rosetta api is properly wired into the provenance binary.  
- [ ] Run the coinbase Rosetta api test against implementation.  
- [ ] (optional) Add Rosetta test to integration test suite as an additional make target.

**Comment by fkneeland-figure** [comment]
I can look into this
