### ISSUE TITLE
OSLocator - second address

### ISSUE THREAD

**Issue by scirner22** [provenance-io/provenance#370]
## Summary

We are now integrating the OSLocator resource and adding replication to object-store. It was realized that the current OSLocator message does not contain enough information for object-store. We're proposing adding a second address to the message that would represent the address associated with the encryption public key.

https://github.com/provenance-io/provenance/blob/e3fef356df6f0d80b196b0e99eca66d0c0841bb5/proto/provenance/metadata/v1/objectstore.proto#L9-L16

### Proposed proto

This is a proposed example. The names don't have to match exactly.

```protobuf
// Defines an Locator object stored on chain, which represents a owner( blockchain address) associated with a endpoint
// uri for it's associated object store.
message ObjectStoreLocator {
  reserved 1;
  reserved "owner";

  // this address signs this tx
  string signing_owner_addr = 3;
  string encryption_owner_addr = 4;
  // locator endpoint uri
  string locator_uri = 2;
}
```

## Background 

Object-store is built off the the Provenance DIME and it the notion of an encryption and signing key. The encryption key is used to generate an ephemeral key that does the actual encryption, and a signing key that signs the dime input stream. This means that an object-store "affiliate" could have an encryption and signing key that are different. Object-store will use the signing key to authenticate incoming messages, and the encryption key will be present in the dime audience list. In order to correctly support the OSLocator message, both of these need to be represented.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Adding the field makes sense ... removing (renaming) the existing owner field as well as the final naming needs a review.  This feature should go into 1.6 along with any required state machine update/migration required.

**Comment by scirner22** [comment]
👍  The concept of the second key is all we need. I'll leave any naming up to your existing conventions.
