### ISSUE TITLE
Evidence Router Configuration for IBC

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#389]
## Summary of Bug

The evidence router configuration needs to be added to the `app.go` to handle slashing conditions.

## Version

1.5.0+

## Remediation

Wire in IBC evidence routes.
```
 app.IBCKeeper.SetRouter(ibcRouter)

  // create static Evidence routers

  evidenceRouter := evidencetypes.NewRouter().
    // add IBC ClientMisbehaviour evidence handler
    AddRoute(ibcclient.RouterKey, ibcclient.HandlerClientMisbehaviour(app.IBCKeeper.ClientKeeper))

  // Setting Router will finalize all routes by sealing router
  // No more routes can be added
  evidenceKeeper.SetRouter(evidenceRouter)

  // set the evidence keeper from the section above
  app.EvidenceKeeper = *evidenceKeeper
  ```

See https://docs.cosmos.network/v0.43/ibc/integration.html for more info.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Note: the router/evidence piece might be out of date in the IBC docs... if this route is no longer required then this issue can be marked as resolved and close after verifying the current IBC configuration.

**Comment by channa-figure** [comment]
The evidence router is no longer needed.  Related ticket (cosmos documentation out of date): https://github.com/cosmos/ibc-go/issues/77
