### ISSUE TITLE
Develop integration test process for provwasm smart contracts

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#392]
## Summary

Develop simulation support for wasm module using provwasm wrapper

## Problem Definition

Currently during the provenanced simulation tests the wasm module is largely left untested.  This presents a risk to the platform.  Basic smart contract execution, export/import, and management features should be exercised during simulation testing of the chain.

## Proposal

Update the provwasm internal wrapper with genesis and operation simulation testing integration.  This integration should be connected using a wrapper that is provided in the app.go simulation manager module registration.

https://github.com/provenance-io/provenance/blob/8d3308794b0521fa02f3746fabb52d3f279ad902/app/app.go#L615

The smart contract(s) used should be as simple as possible.  Basic invocation, loading, and management tests are the overall goal.  Testing/querying against the module (for example transfers using marker) could be added as a future item if required but for now should remain part of a separate integration testing process.

- [ ] Create a module wrapper in the provwasm internal package
- [ ] Add genesis sim support that instantiates with a trivial smart contract
- [ ] Add operation sim support that executes a variety of contract management functions and most importantly many contract executions.

For examples of contracts that can be used for testing see the [wasmit](https://github.com/provenance-io/wasmit) repository.

CC: @dpederson-figure and @ktalley-figure as provwasm code owners.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by fkneeland-figure** [comment]
Completed in v1.8.0. When that is merged to main we can mark this as done.
