### ISSUE TITLE
Upgrade swagger 2.0 to openapi 3.0

### ISSUE THREAD

**Issue by fkneeland-figure** [provenance-io/provenance#404]
## Summary

Openapi 3.0 is the updated version of swagger 2.0.  It has several nice features to make api documentation easier so we should investigate how much work it will take to migrate and whether it is possible with cosmos still using swagger 2.0.

Also should take note of: https://github.com/cosmos/cosmos-sdk/issues/7620

Here is an article explaining some of the differences between swagger 2.0 and openapi 3.0: https://medium.com/@tgtshanika/open-api-3-0-vs-swagger-2-0-94a80f121022

## Proposal
Investigate the feasibility of upgrading swagger 2.0 to openapi 3.0 and make the migration if benefitial. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
This appears to now be a copy of #2063.
Closing this one in favor of that one.
