### ISSUE TITLE
Add support for secondary public key signing of type secp256r1

### ISSUE THREAD

**Issue by channa-figure** [provenance-io/provenance#408]
## Problem Definition

Support a secondary public key for existing accounts of secp256r1.

## Proposal

Add support for secondary public key signing on existing accounts such that an account can have a second public key added of secp256r1 type added/removed based on primary key control

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
This approach isn't really going to work very well... and the authz module allows a primary account to grant another account specific actions now so I don't think we will actually need this.
