### ISSUE TITLE
createAppAndExport does not send the correct wasm home directory to wasm keeper

### ISSUE THREAD

**Issue by channa-figure** [provenance-io/provenance#457]
## Summary of Bug

When running the `export` command wasm contracts are not found and the process panics.  The whole export process fails at this point.  This is due to the home path of wasm keeper not being set correctly during the export setup.  

https://github.com/provenance-io/provenance/blob/1e0747d62f15290a11752695cfe4b9f50235de67/cmd/provenanced/cmd/root.go#L296

We are setting the home directory to `""` in the code above.

The correct home path should match how the wasmd keeper is being setup in the app.go

https://github.com/provenance-io/provenance/blob/463e4e11272407a7d5e0978c28dabba5db0f3f15/app/app.go#L422

Proposed fix would be to setup the wasm home path from command parameter or default to `""`

## Version

 v1.5.0 

## Steps to Reproduce

With a chain that has wasm contracts loaded.  

1.) `provenanced export -t --home <homedir>`

Produces: 

`panic: Error calling the VM: Cache error: Error opening Wasm file for reading: No such file or directory (os error 2)`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Previously identified here: https://github.com/cosmos/cosmos-sdk/issues/8150 and resolved in this PR https://github.com/cosmos/cosmos-sdk/pull/8194
