### ISSUE TITLE
Consider the value owner when deleting a scope

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#473]
## Summary

When deleting a scope, the value owner should be taken into consideration.

## Problem Definition

Currently, when updating a scope's `ValueOwner` field, 
* If the existing value is a marker, one of the signers must have `Access_Withdraw` authority on the marker.
* If the existing value isn't a marker (and isn't empty) it must also be one of the signers.

However, when a scope is being deleted, only the owners must sign. This could be used to circumvent the update requirements on the `ValueOwner` field.

## Proposal

When deleting a scope, if the `ValueOwner` isn't empty:
* If it's a marker, one of the signers must have `Access_Withdraw` authority on the marker.
* Otherwise, it must also be one of the signers.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Thinking more about this it would be withdraw access and not delete as delete is for the marker itself and withdraw/deposit are used for aggregate asset modification.
