### ISSUE TITLE
Tendermint v0.37 config migration

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#518]
## Summary

The Tendermint v0.35 release will have a whole bunch of config file changes that we will need to address to help with updating.

## Problem Definition

1. All underscores in config keys have changed to dashes.
2. Some config keys have been moved to sub-sections and/or renamed.
3. There are several new entries.

## Proposal

Once Tendermint v0.35 is released, review the final changes to make sure this is all still applicable.

The following fields are moving:
* `priv_validator_key_file` -> `priv-validator.key-file`
* `priv_validator_state_file` -> `priv-validator.state-file`
* `priv_validator_laddr` -> `priv-validator.laddr`
* `fast_sync` -> `blocksync.enable`
* `fastsync.version` -> `blocksync.version`
* `statesync.chunk_fetchers` -> `statesync.fetchers`
* `tx_index.indexer` string -> `tx-index.indexer` []string
* `tx_index.psql-conn` (in config struct but not file) -> `tx-index.psql-conn`
* `p2p.seed_mode` -> `mode`: if `seed_mode` = true then `mode` = `"seed"` else `mode` = `"full"`.
* All other fields with a `_` in them are moving to the same field name with `-` instead.

It's possible that other fields are changing types as that comparison has not yet been made.

There is a new `other` field in the config struct that gets populated with entries not mapped to struct fields. It is unclear if this will pick up sub-config fields too. E.g. I don't know if it will contain `tx_indexer.indexer` if an old config file is read using v0.35 structs. If it does contain those entries, this all becomes a lot easier. So for now, let's assume that happens.

As part of the change that bumps the tendermint version to 0.35, we need to also check for old versions of the config file and migrate+replace it if found. When loading unpacked config files, check the new `other` map for a `fast_sync` entry. if found, we need to migrate.

To migrate an unpacked config:
1. We already have a new version of the config object created by reading the old file.
1. Create a field map from it (using `reflector.go`).
1. Go through the special cases listed above and get their value from the `other` map, and use the field map to set the new field appropriately. Delete the entry from `other`.
1. Go through all the rest of the keys in `other`, change the `_`s to `-`s in the key name and use the field map to set the new field to the old value.
1. Save the new config over the old one.

If the config is packed, after reading in the json, go through all the keys. If any of them have an underscore or any of the special cases, it needs to be migrated. Note that, right now, all the special cases have underscores, but that might change by the time it's finalized.

To migrate a packed config:
1. Create a new map[string]string to represent the new packed conf json.
1. Go through all the keys in the old packed config.
1. If it's a special case, change the key and value accordingly and add them to the new packed conf.
1. Otherwise, if the key has an underscore, create a new key that has dashes instead. If the key with dashes is a Tendermint config key, add the value with the new key to the new packed config.
1. Otherwise, add the value with the old key to the new packed conf.
1. Apply the new packed config to the config structs as normal.
1. Generate and write the new packed config using the new config structs.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
Update:
I found that the `other` field only contains base-level entries that weren't mapped. For example, `db_backend` (string), `fast_sync` (bool), and `fastsync` (sub-config)`. But it does not contain sub-config entries, e.g. `statesync.chunk_fetchers` or `p2p.addr-book-file`.

So we can't just use the `other` field to handle all the changeover stuff.

There might be a way to do it by providing a map[string]interface{} to the viper unmarshal func, but that'll take some looking into.

**Comment by SpicyLemon** [comment]
Closing. Can reopen if `_` to `-` change ends up being a thing.
