### ISSUE TITLE
Tendermint v0.35 BaseConfig.Other field and ignored fields

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#519]
## Summary

The Tendermint v0.35 changes include the addition of an `Other` field to `BaseConfig`:
```golang
Other map[string]interface{} `mapstructure:",remain"`
```
We don't want this to be visible with the `provenanced config` commands.
There is also a new test field that should be ignored: `p2p.test-dial-fail`.

## Problem Definition

Hide the `other` and `p2p.test-dial-fail` keys from `provenanced config` commands.

## Proposal

For the `other` field, there are two options:
1. Update the field map generator (in `reflector.go`) to ignore `mapstructure:",remain"` tagged fields.
2. Update `removeUndesirableTmConfigEntries` to ignore the `other` field.

Some research will be needed on mapstructure in comparison to the `reflector.go` stuff to see if option 1 is appropriate.

For the `p2p.test-dial-fail` field, the `removeUndesirableTmConfigEntries` should be used to handle it. That func currently has some stuff to exclude fields that start with `p2p.test_`. Those fields no longer exist in v0.35, so that exclusion can be removed and replaced with either a similar exclusion of `p2p.test-` or for the `p2p.test-dial-fail` field specifically.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Closing. Can reopen later if it ends up being a thing.
