### ISSUE TITLE
specified hd path for dev net key creation

### ISSUE THREAD

**Issue by tsilva-figure** [provenance-io/provenance#532]
## Summary
Custom hd path for local dev net setup.

## Problem Definition
Some developers utilizing the dev network config locally (single node setup), have apps utilizing keys that are not configured to use the default production hash hd path.

## Proposal
Allow an optional hd path argument to be passed to the Dockerfile accessible to the entrypoint script. The hd path arg would simply be sourced from an environment variable HD_PATH.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
HD-path is deprecated... we should review options for long term support here (like using an existing keychain?)
