### ISSUE TITLE
Node unable to join peers

### ISSUE THREAD

**Issue by areller** [provenance-io/provenance#551]
## Summary of Bug

I run a non validator provenance node, this is my `config.toml` file https://www.codepile.net/pile/dZy8kgR4

List of seeds: `4bd2fb0ae5a123f1db325960836004f980ee09b4@seed-0.provenance.io:26656,048b991204d7aac7209229cbe457f622eed96e5d@seed-1.provenance.io:26656`
List of persistent peers: `9e9c66cc7e22ef2be11a02a944c4d150ed742f52@rpc-0.provenance.io:26656,738b4657416504d79af3e9bf45f4a2a813d2fbd6@rpc-1.provenance.io:26656,eea0ff9ac8c228d7827100fcb00cb9b1f5274db6@rpc-2.provenance.io:26656,87592d58ecd6a56bfb4e6fbb96111ec9a6918dc9@rpc-3.provenance.io:26656`

genesis file: https://raw.githubusercontent.com/provenance-io/mainnet/main/pio-mainnet-1/genesis.json

When I run the node via `cosmovisor start`, It would sometimes work and start indexing blocks, but sometimes it would keep printing these errors

```
9:25PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
9:25PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"87592d58ecd6a56bfb4e6fbb96111ec9a6918dc9","ip":"34.86.169.154","port":26656}
9:25PM INF Reconnecting to peer addr={"id":"87592d58ecd6a56bfb4e6fbb96111ec9a6918dc9","ip":"34.86.169.154","port":26656} module=p2p
9:25PM INF Dialing peer address={"id":"87592d58ecd6a56bfb4e6fbb96111ec9a6918dc9","ip":"34.86.169.154","port":26656} module=p2p
9:25PM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
9:25PM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
9:25PM INF Starting Peer service impl="Peer{MConn{34.94.27.30:26656} 738b4657416504d79af3e9bf45f4a2a813d2fbd6 out}" module=p2p peer={"id":"738b4657416504d79af3e9bf45f4a2a813d2fbd6","ip":"34.94.27.30","port":26656}
9:25PM INF Starting MConnection service impl=MConn{34.94.27.30:26656} module=p2p peer={"id":"738b4657416504d79af3e9bf45f4a2a813d2fbd6","ip":"34.94.27.30","port":26656}
9:25PM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
9:25PM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"738b4657416504d79af3e9bf45f4a2a813d2fbd6","ip":"34.94.27.30","port":26656}
9:25PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"738b4657416504d79af3e9bf45f4a2a813d2fbd6","ip":"34.94.27.30","port":26656}
9:25PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
```

And just get stuck

## Version

v1.7.4 tag

## Steps to Reproduce

Use the configuration above, run via cosmovisor

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by channa-figure** [comment]
Hi @areller , Could you try and remove the persistent peers from your configuration and see if that resolves the issue?

**Comment by iramiller** [comment]
(For future reference there are a lot of nodes out there that attempt to use these central nodes for peers and they are typically full and not accepting additional connections for exchange)

**Comment by areller** [comment]
@channa-figure @iramiller I'll try it tomorrow, I'll let you know if it helps
Thank you
