### ISSUE TITLE
Capture all included protobufs into release zip file

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#556]
## Summary

Currently there are some third party dependency protos that are part of data on chain associated with our releases that are not included in our proto zip file release

## Problem Definition

By not capturing all of the protos from third party dependencies like wasmd in our proto files clients are required to track down these dependencies when they need to decode this data.  This is extra complicated because some of the protos change with the dependency version changes

## Proposal

Ensure that all third party dependency protos are copied into the release proto zip file.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
Note on this: we want to makes sure we use ultimate source of truth on the protos. so cosmos comes from cosmos, ibc comes from ibc, and wasm comes from wasm. Also, pulling ALL protos, not just used protos.

**Comment by crussell-figure** [comment]
See here: https://github.com/provenance-io/explorer-service/blob/main/buildSrc/src/main/kotlin/io/provenance/DownloadProtosTask.kt for what protos are needed
