### ISSUE TITLE
Marker governance control flag not persisted

### ISSUE THREAD

**Issue by vwagner** [provenance-io/provenance#558]
## Summary of Bug

When creating a Marker, if `allowGovernanceControl` is set to `false`, the value is not persisted on chain. When subsequently querying for the Marker, `allowGovernanceControl` comes back as `true`.

## Version

v1.7.3

## Steps to Reproduce

Using grpc client, create a `MsgAddMarkerRequest` with `allowGovernanceControl = false`. After finalizing and activating, query to Marker. Governance control flag comes back as true.

Example running on my localnet:

**MsgAddMarkerRequest**
```json
{
  "amount" : {
    "denom" : "nft.7f856c21-85c9-4543-aa49-6c504c0828f1",
    "amount" : "1"
  },
  "manager" : "tp1dhydmg53h39d7x2txpn4ycen4t0d5h3d2swx6r",
  "fromAddress" : "tp1dhydmg53h39d7x2txpn4ycen4t0d5h3d2swx6r",
  "status" : "MARKER_STATUS_FINALIZED",
  "markerType" : "MARKER_TYPE_COIN",
  "accessList" : [ {
    "address" : "tp1dhydmg53h39d7x2txpn4ycen4t0d5h3d2swx6r",
    "permissions" : [ "ACCESS_DEPOSIT", "ACCESS_WITHDRAW" ]
  } ],
  "supplyFixed" : true,
  "allowGovernanceControl" : false
}
```

**MsgActivateRequest**
```json
{
  "denom" : "nft.7f856c21-85c9-4543-aa49-6c504c0828f1",
  "administrator" : "tp1dhydmg53h39d7x2txpn4ycen4t0d5h3d2swx6r"
}
```

**Marker account query returns:**
```json
{
  "baseAccount" : {
    "address" : "tp10zn7x5m8tmjp52wqjcqv9njsrnenq6ujuc0lwr",
    "accountNumber" : 20,
    "sequence" : 0
  },
  "manager" : "",
  "accessControl" : [ {
    "address" : "tp1dhydmg53h39d7x2txpn4ycen4t0d5h3d2swx6r",
    "permissions" : [ "ACCESS_DEPOSIT", "ACCESS_WITHDRAW" ]
  } ],
  "status" : "MARKER_STATUS_ACTIVE",
  "denom" : "nft.7f856c21-85c9-4543-aa49-6c504c0828f1",
  "supply" : "1",
  "markerType" : "MARKER_TYPE_COIN",
  "supplyFixed" : true,
  "allowGovernanceControl" : true
}
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
The governance flag can be force set to true using the parameter configuration of the marker module, in this case for provenance blockchain mainnet we require governance management of all created markers
```
%%> provenanced q marker params
enable_governance: true
max_total_supply: "100000000000000"
unrestricted_denom_regex: '[a-zA-Z][a-zA-Z0-9\-\.]{7,64}'
```

**Comment by iramiller** [comment]
Details here: 
https://github.com/provenance-io/provenance/blob/e3fef356df6f0d80b196b0e99eca66d0c0841bb5/x/marker/keeper/msg_server.go#L66-L71

**Comment by vwagner** [comment]
Got it, thanks.
