### ISSUE TITLE
[Security] Workflow test.yml is using vulnerable action codecov/codecov-action

### ISSUE THREAD

**Issue by Freakston** [provenance-io/provenance#576]
The workflow test.yml is referencing action codecov/codecov-action using references v1.3.1. However this reference is missing the commit [c6a36d2dbbf6a734e6ef75af344acdf122fcd9f9](https://github.com/codecov/codecov-action/commits/c6a36d2dbbf6a734e6ef75af344acdf122fcd9f9) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by iramiller** [comment]
https://github.com/provenance-io/provenance/blob/35541ddee9f832b4061192f792df687f7b7b66c2/.github/workflows/test.yml#L149

We are currently using CodeCov 2.1 in our `test.yml`. Where are you seeing 1.3.1 referenced?

**Comment by Freakston** [comment]
Sorry about the issue report. This was generated automatically by a tool a while ago. Thanks for letting me know.
