### ISSUE TITLE
Fix iavl config size parsing in cosmos-sdk

### ISSUE THREAD

**Issue by channa-figure** [provenance-io/provenance#608]
Cosmos-sdk had added a configuration for the iavl-cache-size, but forgot to add it to the GetConfig parsing logic.  I added it to our fork and made an upstream PR.  They are going to backport it into v0.45.0 release.

Cosmos-sdk issue: https://github.com/cosmos/cosmos-sdk/issues/10982
Cosmos-sdk PR: https://github.com/cosmos/cosmos-sdk/pull/10990

**Comment by arnabmitra** [comment]
i think this can be closed @nullpointer0x00  ?
