### ISSUE TITLE
Set Fee Schedule in 1.8.0 Upgrade

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#616]
## Summary

As part of the 1.8.0 release the new msg fee module exposes important capabilities for spam control.  Add a new set of base fees to the upgrade handler in 1.8.0 to ensure that base operations have initial fees set

## Problem Definition

Controlling spam and creation of large amount of assets on chain can be done through gas to a limited extent.  Extending these controls is performed with msg based fees on select operations.

## Proposal

- Limit the maximum attribute value length to 1000 (down from 10,000 currently)
- Add Msg Fees for select operations 
   - provenance.name.v1.MsgBindNameRequest (10HASH)
   - provenance.marker.v1.MsgAddMarkerRequest (100HASH)
   - provenance.attribute.v1.MsgAddAttributeRequest (10HASH) 
   - provenance.metadata.v1.MsgWriteScopeRequest (10HASH)
   - provenance.metadata.v1.MsgP8eMemorializeContractRequest(10HASH)

Note: based on current pricing 10HASH is $1 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Based on analysis of mainnet attributes the largest ones are for passport records ... and are approximately 480 bytes in length meaning the 1000 byte limit above is more than double the current active use.

**Comment by arnabmitra** [comment]
kotlin example of estimating fee for msg's which may or may not have additional fee here https://github.com/arnabmitra/pb-grpc-client-kotlin/blob/572731e37edc4b970fe6723a208cbfcd1085f6dc/src/main/kotlin/io/provenance/client/grpc/PbClient.kt#L126

**Comment by channa-figure** [comment]
Can we add some logging for these in the upgrade handler?  Also, I can run some scripts with these txs to simulate and to execute these transactions to confirm that they work. 1.) upgrade from 1.7.6 to 1.8.0 locally 2.) run simulate and tx for each of the cases stated above.
