### ISSUE TITLE
Add support for event data injection into end block handlers

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#626]
## Summary

Currently the Cosmos SDK End block methods are only provided with the block height as a parameter, this feature would inject the events from block processing to support more advanced reactive features.

## Problem Definition

Adding a new incentive module that tracks on chain activity for incentive distribution will require insight into the transactions which have been processed in each block.  Due to the design of the current sdk each module is completely isolated and there is not a clean way to monitor another modules activities.  

Adding support for event history collection and making this available in the end block context will allow monitoring of all activity within a block without explicit hooks being created.

This global insight to all activities within a block will allow the incentive module to provide custom tracking functions based on user activity for rewards distribution.

While adding these changes require a custom fork of the Cosmos SDK, it is expected that a longer term solution is coming in v0.47 that we can migrate to and obsolete this custom implementation.

## Proposal

A previously proposed solution that implements this features is here: https://github.com/cosmos/cosmos-sdk/pull/9305

Develop a similar solution for the Provenance Cosmos SDK fork that injects event history into the end block using a custom extended event manager with history tracking.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by arnabmitra** [comment]
this was merged as part of the 0.45.4 and 0.46.+ changes to main, closing the issue
