### ISSUE TITLE
Chain panic on contract execution 

### ISSUE THREAD

**Issue by channa-figure** [provenance-io/provenance#655]
## Summary of Bug

There is an issue with cosmwasm v1.0.0-beta5 that caused a panic and halted the chain on executing a contract. This is fixed in cosmwasm v1.0.0-beta6 https://github.com/CosmWasm/cosmwasm/pull/1223

Other chains have experienced this as well.  https://github.com/CosmosContracts/juno/pull/156

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
release in RC6
