### ISSUE TITLE
Additional Event type for msg fees broken down by msg type for client(Explorer) consumption

### ISSUE THREAD

**Issue by arnabmitra** [provenance-io/provenance#678]
## Summary

Additional Event type for msg fees broken down by msg type

## Problem Definition

In some conversation with the explorer team, they suggest that clients may want to see additional fee broken down by the type of message that it was charged on.
For e.g If two markers were created and both were bound to names and lets say all these operations were charged fees, the explorer would like an event showing fee breakdown per MsgType(at least from my understanding, per operation would be harder, since i believe we only keep tally by MsgType) 
For above example let's say Create Marker has a 100hash additional fee and BindName has 10hash,
We would expect to see an Event similar to: 
```
{
  type: EventMsgFee,
  attributes: [
    {
       key : "/provenance.metadata.v1.MsgWriteScopeRequest"
       value :"1000000000nhash",
count: 3
    },
    {
       key : "/provenance.metadata.v1.CreateMarkerRequest"
       value :"100000000000nhash",
count: 1
    },
    {
       key : "totalMsgFee"
       value : 320000000000nhash,
count: 1
    },
  ]
}
```
We should create a new event to represent the above data.

Are there any disadvantages of including this feature? 
It adds more event data, which can be significant, imagine a MultiTx with significant amount of Msg fee charged for each sub Tx.(However there are not that many disparate messages in the system.

## Proposal
1. Add a counter to `FeeGasMeter`
2. Create a new event type
3. Change BaseApp.go to emit these events at the end of a successful `runTx`
4. Keep Older events same?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by channa-figure** [comment]
I think this should work for wasm and authz request if we emit the events in the msg router https://github.com/provenance-io/provenance/blob/main/internal/handlers/msg_service_router.go#L145.
