### ISSUE TITLE
Update the scope object to include a new property for tracking expiration blockheight

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#694]
Update the protobuf for scopes to include a new property for tracking the blockheight that a scope is valid until.  Ensure that this field is backwards compatible with existing data such that if a scope does not have an expiration set a default expiration blockheight value will be used instead... this value will be set during the module migration process that is performed when upgrading.  Any future updates to the scope or its records can use the default assignment of current blockheight plus the extension duration to set the new expiration height

**Comment by egaxhaj** [comment]
Work has moved to #957
