### ISSUE TITLE
Create SECURITY contact and reporting guideline

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#7]
Setup the SECURITY.md file for the provenance blockchain project.  Ensure that issue templates correctly reference the security reporting document/contacts.  Reference upstream security reporting process (COSMOS-SDK) as required.

**Comment by iramiller** [comment]
@rjmarkel it seems like this work is done.  Was there something else you planned to add or can this be closed out?

**Comment by rjmarkel** [comment]
Nothing else - this can be closed out.

**Comment by iramiller** [comment]
Complete.
