### ISSUE TITLE
Update to wasmd 1.0 final

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#742]
## Summary

Currently the wasmd module is using a beta version of the wasmvm which pulls in wasmer 2.2.x.  Update to the final release of wasmd when available (before 1.9.0 is released)

## Problem Definition

Currently the software is using a beta version of the wasmer vm which we do not want to ship in 1.9.x

## Proposal

Update dependencies to release versions.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kwtalley** [comment]
superseded by #1015
