### ISSUE TITLE
Fix sim tests so that they pass.

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#754]
## Summary of Bug

At least a couple of the sim tests fail due to insufficient funds. These failures might end up masking other, more serious failures.

## Version

`main`

## Steps to Reproduce

The following commands result in the following errors:
* `make test-sim-after-import` -> "panic: expected validator, not found"
* `make test-sim-nondeterminism-state-listening-file` -> "panic: stored minter should not have been nil"
* `make test-sim-nondeterminism-state-listening-trace` -> "panic: stored minter should not have been nil"
* `make test-sim-nondeterminism-state-listening-kafka` -> "panic: stored minter should not have been nil"

Once fixed, the `.github/workflows/sims.yml` file should be updated too, so that those tests run.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
After some more digging, I found that the following sims are broken:
* `after-import`: "panic: expected validator, not found"
* `test-sim-nondeterminism-state-listening-file`: "panic: stored minter should not have been nil"
* `test-sim-nondeterminism-state-listening-trace`: "panic: stored minter should not have been nil"
* `test-sim-nondeterminism-state-listening-kafka`: "panic: stored minter should not have been nil"
I've updated the issue to reflect this.

**Comment by SpicyLemon** [comment]
No longer an issue. the state listening ones were removed and the after-import sim has been fixed.
