### ISSUE TITLE
Slashing endpoint gives back empty array for validator we know got slashed

### ISSUE THREAD

**Issue by arnabmitra** [provenance-io/provenance#771]
## Summary of Bug

Someone on provenance discord was complaining that they could not query for slashing events even though they knew the validator had been slashed,
I tried this on pio-mainnet (command line and rpc-gateway)

https://api.provenance.io/cosmos/distribution/v1beta1/validators/pbvaloper1rmdadg0ve4qu3yjnusyxjtuag6egx6uj9xesg9/slashes?starting_height=100000&ending_height=4831513

and got the same result.

## Version

v1.8.0 release

## Steps to Reproduce

https://api.provenance.io/cosmos/distribution/v1beta1/validators/pbvaloper1rmdadg0ve4qu3yjnusyxjtuag6egx6uj9xesg9/slashes?starting_height=100000&ending_height=4831513

see details of the validator https://explorer.provenance.io/validator/pbvaloper1rmdadg0ve4qu3yjnusyxjtuag6egx6uj9xesg9 
(it has been jailed for sure)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
It sounds like this is a pruning height issue...

**Comment by arnabmitra** [comment]
yeah good point, probably is pruning
