### ISSUE TITLE
Update to go 1.18

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#800]
## Summary

Increment the go language version from 1.17 to 1.18

## Problem Definition

Update to the latest version of go to receive the improvements outlined here: https://tip.golang.org/doc/go1.18

## Proposal

Update the go mod and all workflow files to target 1.18 from the exsting 1.17 version of go.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Taztingo** [comment]
It would be really beneficial to M1 users if we upgraded to golang 1.8.2. 1.8.2 adds the required features to allow M1's to properly debug with delve and make function calls.
