### ISSUE TITLE
provenanced: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by afacchibd** [provenance-io/provenance#804]
## Summary of Bug

root@9384e7426c9a:/usr/local/bin# ldd provenanced
	linux-vdso.so.1 (0x00007ffd037fb000)
	libleveldb.so.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc4f42a0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc4f429a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc4f414b000)
	libwasmvm.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc4f3f59000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc4f42c7000)

## Version

v1.9.0

## Steps to Reproduce

$ provenanced version --long
provenanced: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
It looks like you're missing both the Level DB and WASM shared libraries. The Level DB libraries can be installed using your favorite package manager; it can also be built/installed using this repo's `make cleveldb` target. The WASM shared library is provided in the zip that also contains `provenanced`.
