### ISSUE TITLE
Add acceptable name bind request format to the provenance docs

### ISSUE THREAD

**Issue by mhellwinkel** [provenance-io/provenance#808]
## Summary

It is currently unclear to end users what the acceptable format is for Names in the name-module.

## Problem Definition
End users should not have to search through Provenance code and decider it to determine what acceptable names are.
https://github.com/provenance-io/provenance/blob/3279e911293c18efb0bb7f0b31d5b0446318dd17/x/name/keeper/keeper.go#L240

## Proposal

Proposed just simply adding the regex format that is acceptable to the documentation. here
https://docs.provenance.io/modules/name-module

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mhellwinkel** [comment]
Is this something somebody could pick up please? Its difficult to relay to outside parties what the acceptable format is here

**Comment by SpicyLemon** [comment]
Our spec docs had a section for this, but that hadn't made it to those other pages.

These PRs were also involved in this:
* https://github.com/provenance-io/docs/pull/26
* https://github.com/provenance-io/provenance-docs/pull/1
