### ISSUE TITLE
librdkafka runtime support for M1

### ISSUE THREAD

**Issue by egaxhaj-figure** [provenance-io/provenance#812]
## Summary of Bug

librdkafka requires extra steps to install correctly on M1 Macs. 

Can we include librdkafka M1 installation steps into a script that can be part of the build process in the Makefile?

## Version

`1.8.x`

## Steps to Reproduce

Build `1.8.1` on mac M1

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
At the very least, we could update the [docs/Building.md](https://github.com/provenance-io/provenance/blob/main/docs/Building.md#librdkafka) instructions to include openssl and the `PKG_CONFIG_PATH` env var.
Basically, for the M1 macs, we also need to make sure openssl is installed: 
```console
$ brew install openssl
```
and that the `PKG_CONFIG_PATH` environment variable includes the openssl lib path: 
```console
$ export PKG_CONFIG_PATH="$( brew --prefix openssl )/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
```
It's already got a note about `librdkafka` on the M1 macs.

If we actually want to update the Makefile to handle all this, we need to make sure it's only done on M1 macs a) if not already done, and b) only if actually needed (e.g. doing a `build` or `install` etc. target).

**Comment by fkohantorabi** [comment]
You will also need to add instructions to install pkg-config as it is not installed by default...at least on Monterey. 

`$ brew install pkg-config`
