### ISSUE TITLE
(DEV Task) Reward Program Pool Balance Entity

### ISSUE THREAD

**Issue by channa-figure** [provenance-io/provenance#828]
## Summary

When a reward program is created coins are sent to the module account for the community pool.  We need a way to keep track of the balance that is in the module for that specific address and program id.

## Proposal

When a reward program is added a new balance entity is added to the keeper to track pool balance.  Every time a reward is claimed the balance must be deducted.  Once the reward program has completed and the reward claim window has passed.  The coins will automatically or manually be sent to the distribution address.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Note: the blockchain community pool is not the same thing as the APE module account... we will actually be doing some funding where we take shares from the actual community pool and use those to run a continuous reward program ...
