### ISSUE TITLE
The specified item could not be found in the keyring

### ISSUE THREAD

**Issue by lhtvineettiwari** [provenance-io/provenance#878]
Having this error while doing the transaction `The specified item could not be found in the keyring`.

Steps to reproduce the error:
```
docker pull provenanceio/provenance
docker run -p 1317:1317 -p 26657:26657 -p 9090:9090 provenanceio/node:pio-testnet-1  
```
This is running the network and even getting the status by running the command `provenanced status` .
But while doing the transaction having this error.
![Screenshot 2022-06-18 at 10 50 04 PM](https://user-images.githubusercontent.com/91462759/174449871-cc8d4eef-d8fd-4752-92ee-99b0d6f2a068.png)

But while querying `provenanced keys list --keyring-backend test -t`, getting the account details.
![Screenshot 2022-06-18 at 10 50 58 PM](https://user-images.githubusercontent.com/91462759/174449905-6611381d-d72a-402d-b637-bf634fa09831.png)

**Comment by arnabmitra** [comment]
a little hard to make out from a screen shot, but what is your `   --from string              Name or address of private key with which to sign`  look like? 

example use of send command here 
```
provenanced -t tx bank send tp16h2lejnpjapaawgyquqhvr6x9wzmmyzjw87huz  tp10es47kqypfg3tt4l02enx7y80dr4e4zndylnze 1000000000000000nhash \
        --from ibc-pio-testnet \
        --keyring-backend os \
        --chain-id pio-testnet-1 \
        --gas auto --gas-prices 1905nhash --gas-adjustment 1.4 --yes \
        --testnet --node=https://rpc.test.provenance.io:443 -o json | jq
```

**Comment by channa-figure** [comment]
Can you try it with adding `--from testkey` and `--keyring-backed test` to your send command?

**Comment by nullpointer0x00** [comment]
Can you try it with adding --from testkey and --keyring-backed test to your send command?

**Comment by lhtvineettiwari** [comment]
After the faucet step, while querying balance, the balance is not showing for the public key.
<img width="1475" alt="Screenshot 2022-06-24 at 1 11 04 AM" src="https://user-images.githubusercontent.com/91462759/175456721-f5fa9a0e-63d2-4410-9040-b6e4eba9cc38.png">

`[$ provenanced --testnet keys add test1 -hd-path="44' /1'/0'/0/0" --home SPIO HOME
- name: test1
type: local
address: tp1ypqzygn3575pwkxva76gz79f9es5s0j6ayz9mn
pubkey:tppub1addwnpepq22crfdf8rwln635dcxrn4rvng7k4p7n5721d24azjfeujyf4rvm7htzysn
mnemonic:
threshold:
pubkeys:
**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.
tide police various atom veteran planet arrow wolf quote guide segment major amused staff during open evoke yellow cluster salon divert public blood drip
$ provenanced
-testnet q bank balances tp1ypqzygn3575pwkxva76gz79f9es5s0jbayz9mn
balances: [1
pagination:
next_key: null
total:
"g"
$ provenanced
-testnet q bank balances tp1ypqzygn3575pwkxva76gz79f9es5s@jbayz9mn -home $PIO_HOME
balances: [1
pagination:
next_key:
null
total: "0"`

**Comment by arnabmitra** [comment]
you need to query a working node `provenanced -t q  bank balances  tp1ypqzygn3575pwkxva76gz79f9es5s0j6ayz9mn --node=https://rpc.test.provenance.io:443` ```balances:
- amount: "100000000000"
  denom: nhash
pagination:
  next_key: null
  total: "0"```

**Comment by lhtvineettiwari** [comment]
Here i am trying top setup a private node, What if i don't want to sync with the running node. Can anyone guide me to work on those steps.

**Comment by arnabmitra** [comment]
https://docs.provenance.io/blockchain/running-a-node/running-a-node-1/join-provenance-testnet
 if you do not want to sync from genesis you can use https://app.gitbook.com/o/-MNPzQ5GXkTboNkPXWa2/s/-MNPy0zXkVfdarbFqMwG/blockchain/running-a-node/running-a-node-1/running-a-mainnet-node-1

**Comment by lhtvineettiwari** [comment]
Thanks @arnabmitra, let me try this one https://docs.provenance.io/blockchain/running-a-node/running-a-node-1/join-provenance-testnet/running-a-testnet-node-from-quicksync and will come back to you.

**Comment by lhtvineettiwari** [comment]
HI @arnabmitra in the referred link i still have to store history-archives and later i will connect with the testnet. So, what if i don't want to join testnet and i want to run a complete private network.

**Comment by arnabmitra** [comment]
should have been resolved by discord
