### ISSUE TITLE
Create a CLI command for estimating block heights.

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#885]
## Summary

Add a sub-command to `provenanced` that will estimate the block height at a given date and time.

## Problem Definition

We usually want to schedule upgrade proposals for a specific date and time. But upgrades need to be scheduled by block height. Several of us have scripts out there to help estimate the block hight for a given date and time, but it'd be nice to have a `provenanced` command to do it.

## Proposal

Create a `provenanced estimate-block [date/time|height]` command.
The output should include details about the desired block and the estimation. Something like this:
Example usage:
```console
$ provenanced estimate-block 2022-06-22 13:00
Chain-Id: pio-testnet-1
Node: https://rpc.test.provenance.io:443
Current: 2022-06-22 11:47:49 -0600 Height: 8719725
Desired: 2022-06-22 13:00:00 -0600 Height: 8720690
Elapsed milliseconds: 4330527 = 965 blocks at 4486 milliseconds per block.
$ provenanced estimate-block 8720690
Chain-Id: pio-testnet-1
Node: https://rpc.test.provenance.io:443
Current: 2022-06-22 11:47:49 -0600 Height: 8719725
Desired: 2022-06-22 13:00:00 -0600 Height: 8720690
Elapsed milliseconds: 4330527 = 965 blocks at 4486 milliseconds per block.
```
* The `[date/time]` input should allow for [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formats. Seconds should be optional (defaulting to `00`). If no time zone/offset is indicated, use the current system's. The `T` between the date and time should be optional, and the command should allow for the date and time to come in as two arguments. E.g. `provenanced estimate-block 2022-06-22 13:00` should work the same as `provenanced estimate-block '2022-06-22 13:00'` and `provenanced estimate-block 2022-06T22 13:00`,
* Include a `--blocks-back` flag that defaults to 1000, and is the number of blocks back to look up in order to estimate the time each bock takes.
* Include a `--ms-per-block` flag that defines the time each block takes (instead of estimating).
* Include a `--current-height` flag that defines the current height to use (instead of looking it up from the current block).
* Include a `--current-date-time` flag that defines the current date/time to use (instead of looking it up from the current block).
* Include a `--verbose` (or `-v`) flag that will, as it goes, output lookups (before and after) and calculations.
* Include a `--simple` flag that will cause output to ONLY be the calculated value (either block height or block time, depending on the input).
  For Example:
   ```console
   $ provenanced estimate-block 2022-06-22 13:00 --simple
  8720690
   $ provenanced estimate-block 8720690 --simple
  2022-06-22T13:00:00Z
   ```

If a `--current-height` is given, but no `--current-date-time`, then use `Date.Now()` for the "current" date/time. If a `--current-date-time` is given without a `--current-height` the current height will still need to be looked up.

Providing all of `--current-height`, `--current-date-time`, and `--ms-per-block` should allow the command to work while offline (i.e. there is nothing that needs to be looked up).

The basic methodology of the command should be:
1. Look up the current block (e.g. `provenanced query block`).
2. Extract the block and time from that result.
3. Look up a previous block. Use the current block height minus the defined blocks-back.
4. Extract that previous block time from that result.
5. Calculate the time that elapsed between the two blocks in milliseconds.
6. Divide that by the number of blocks that elapsed (blocks back) to get milliseconds per block.
7. Calculate the desired value:
   * If a desired date/time was provided:
      1. Calculate the time between the current block's time and the desired time (in milliseconds).
      2. Divide that by the milliseconds per block to get the number of blocks that will (probably) be cut by then.
      3. Add that number of blocks to the current block height to get the block height at the desired time.
   * If a desired height was provided:
      1. Calculate the number of blocks between the desired height and current height.
      2. Multiply that by milliseconds per block to get the amount of time that will (probably) elapse by then.
      3. Add that to the current block's date/time to get the time at the desired height.
8. Do the final output.

If `--current-height` is provided, steps 1-2 can be skipped (get the current time from either `--current-date-time` or `Date.Now()`).
If `--ms-per-block` is provided, steps 3-6 can be skipped.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
As a Note: estimated block time can be affected by upgrades that occurred during the `blocks-back` set. Might wanna toss those extreme outliers via standard deviation, etc

**Comment by arnabmitra** [comment]
@Taztingo i believe you have a script that does this? can you close it, if it completes this issue

**Comment by arnabmitra** [comment]
> @Taztingo i believe you have a script that does this? can you close it, if it completes this issue

nm .. it's only a script..so probably not done as the issue specifies

**Comment by SpicyLemon** [comment]
The more I think about this, the more I think this functionality is best left to outside scripts. There's just too much complexity and different ways to look at things. Plus, sites like Mintscan will give an estimate if you navigate to the page for a future block, and that's probably good enough for most use cases.
