### ISSUE TITLE
Remove ADR 038 from upstream release-pio/v0.45.x

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#918]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Is this still required? I believe that @SpicyLemon is removing these pieces fully in his 0.46 update as well..

**Comment by SpicyLemon** [comment]
Yeah.
1. We shouldn't be needing to update our `v0.45.x` stuff anymore (unless we're planning another release that I don't know about between `v1.12` and our release with `v0.46.x` in it).
2. I've already removed it from our `v0.46.x` stuff (see #1016).
3. "Upstream" would be the primary cosmo-SDK repo, which wouldn't have the `release-pio/...` branches and releases.

**Comment by iramiller** [comment]
Completed with the move to 0.46
