### ISSUE TITLE
Add simulation support to the marker module

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#94]
## Summary

The marker module currently does not have simulation support.  This capability needs to be added to ensure stability of the entire blockchain long term.

## Proposal

Add simulation support to the blockchain module.

- [ ] State encoder/decoder support
- [ ] Parameter proposal change support
- [ ] Governance proposal support
- [ ] mint/burn calls against markers
- [ ] Restricted markers and transfers 
- [ ] state transitions (proposed, finalized, active, deleted)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Marker module has simulation support.
