### ISSUE TITLE
Backport x/nft to our 0.45.x branch in our Cosmos-SDK fork

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#958]
## Summary

Add the x/nft module to our 0.45-based Cosmos-SDK branch.

## Problem Definition

The `x/nft` module is part of Cosmos-SDK 0.46, which hasn't been released yet. Since we don't know when it'll get released, but we want to use that module, we'll need to backport it to our own `release-pio/v0.45.x` branch.

## Proposal

Copy the `x/nft` directory from the most recent 0.46 release candidate into `release-pio/v0.45.x`. Then identify and make any other changes needed to allow us to use the `x/nft` module with our own 0.45.x based version of Cosmos-SDK.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Since we are looking at going with the actual 0.46 release now it seems like we won't need to copy over these files into our fork on 0.45

**Comment by SpicyLemon** [comment]
A bit ago, I put together the branch: `prov/dwedul/958-nft-backport-to-0.45.x`. I'm pretty sure it's got everything, but never got around to doublechecking (e.g. running unit tests). I'll keep it around just in case we do actually end up needing it in 0.45.x. But for now, I'll just close this issue.
