### ISSUE TITLE
Create Scaffolding for Asset Expiration Module

### ISSUE THREAD

**Issue by derekadams** [provenance-io/provenance#961]
## Summary

The asset expiration functionality will be created in a new `x/expiration` Cosmos module. Standard scaffolding will be required in order to implement the new module.

## Problem Definition

The asset expiration module will require the standard Cosmos module scaffolding aspects such as module interfaces, keeper, and client/queries. 

## Proposal

This scaffolding can be created without having the module implementation completely specified and should be completed in order to act as the basis for the final implementation.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by egaxhaj** [comment]
closing this (Github failed to auto close). Fixed by #1024
