### ISSUE TITLE
RPC calls for Provenance

### ISSUE THREAD

**Issue by Palak3196** [provenance-io/provenance#966]
Hi Team,

We are running a Provenance mainnet node with image: provenanceio/node:pio-mainnet-1
The provenanced commands work within the container.
But we're looking for some rpc calls we can make against the mainnet archival node.

**Comment by iramiller** [comment]
What kind of RPC calls and against which node? How much history?  These kinds of questions are best asked over on our discord...  https://discord.gg/kNZC8nwCFP

**Comment by SpicyLemon** [comment]
Closing this as stale.
