### ISSUE TITLE
(DEV TASK) Create a query that can inform users about their claims.

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#967]
## Summary

A user should be able to get information about their claims. Their claim information should contain its claimable state, their reward, and what reward program it belongs to.

## Problem Definition

Users are unable to tell if they have claim unless they make a claim transaction. This can be problematic if users unintentionally participate in a reward program and don't know they have a claim. Issues can also arise if the reward is less than the transaction cost.

## Proposal

A new query that allows the user to specify a reward program id and a claim state.
provenanced query reward claims [reward_program_id] [all | claimable | claimed | expired | unclaimable]

The query should return a list of claims that match the specified filters.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by arnabmitra** [comment]
done
