### ISSUE TITLE
Snapshot Approach does not work

### ISSUE THREAD

**Issue by debasish22** [provenance-io/provenance#982]
@arnabmitra 
Provenance snapshot approach starts the node from the start of the block on which snapshot was taken - https://tools.highstakes.ch/snapshots/provenancet.

This does not have blocks from the start like block 1. Can any one help here if we are missing anything. Our requirement is for an archival node.The start block of our node is 6622001.

**Comment by arnabmitra** [comment]
archival nodes are found here https://provenance.io/quicksync

**Comment by debasish22** [comment]
Hello @arnabmitra we did start the blockchain from genesis and it got stuck at particular blockheight - 35199  and that's where this issue was raised on this particular link and we ended up with snapshot approach which does not have the archival data.Can you please again take a look and help us in this matter .
 https://github.com/provenance-io/mainnet/issues/21

**Comment by arnabmitra** [comment]
> Hello @arnabmitra we did start the blockchain from genesis and it got stuck at particular blockheight - 35199 and that's where this issue was raised on this particular link and we ended up with snapshot approach which does not have the archival data.Can you please again take a look and help us in this matter . [provenance-io/mainnet#21](https://github.com/provenance-io/mainnet/issues/21)

Hello @debasish22 as mentioned in the previous comment you will need the right binaries at various upgrade heights, the provenance chain has undergone a few upgrades since launch, the list can be found here https://explorer.provenance.io/network/upgrades , you can also check the governance proposal for each of them on the governance tab.
When the chain hits an upgrade height it needs the appropriate binary is to be used.
352000 <-- is the first upgrade height and hence your chain will stop 352000 -1 
We use the cosmos sdk upgrade module in case you are curious on details  https://docs.cosmos.network/master/modules/upgrade/

**Comment by arnabmitra** [comment]
docker releases found here https://hub.docker.com/r/provenanceio/provenance/tags?page=2 

regular releases here https://github.com/provenance-io/provenance/releases

**Comment by debasish22** [comment]
@arnabmitra We tried the quicksync approach but the tar file download fails with the belowissue.

we have set up the node using the below command - docker run -it --rm --name my-node -p 1317:1317 -p 26657:26657 -p 9090:9090 -v $(pwd)/mynode:/home/provenance provenanceio/node:pio-mainnet-1

once the snapshot works can you help us with the pruning key to be added to the above command.

Issue while downloading the snapshot :

"--2022-08-02 05:12:16--  https://storage.googleapis.com/download/storage/v1/b/provenance-mainnet-backups/o/2021-10-12-data.tar.gz?generation=1634332705015691
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.21.128, 108.177.122.128, 142.250.176.80, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.21.128|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-08-02 05:12:16 ERROR 400: Bad Request."
"

**Comment by arnabmitra** [comment]
> @arnabmitra We tried the quicksync approach but the tar file download fails with the belowissue.
> 
> we have set up the node using the below command - docker run -it --rm --name my-node -p 1317:1317 -p 26657:26657 -p 9090:9090 -v $(pwd)/mynode:/home/provenance provenanceio/node:pio-mainnet-1
> 
> once the snapshot works can you help us with the pruning key to be added to the above command.
> 
> Issue while downloading the snapshot :
> 
> "--2022-08-02 05:12:16-- https://storage.googleapis.com/download/storage/v1/b/provenance-mainnet-backups/o/2021-10-12-data.tar.gz?generation=1634332705015691 Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.21.128, 108.177.122.128, 142.250.176.80, ... Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.21.128|:443... connected. HTTP request sent, awaiting response... 400 Bad Request 2022-08-02 05:12:16 ERROR 400: Bad Request." "

1.
your app.toml has the pruning key set up ..comments are pretty elaborate
# default: the last 100 states are kept in addition to every 500th state; pruning at 10 block intervals
# nothing: all historic states will be saved, nothing will be deleted (i.e. archiving node)
# everything: all saved states will be deleted, storing only the current and previous state; pruning at 10 block intervals
# custom: allow pruning options to be manually specified through 'pruning-keep-recent', 'pruning-keep-every', and 'pruning-interval'
pruning = "default"

# These are applied if and only if the pruning strategy is custom.
pruning-keep-recent = "0"
pruning-keep-every = "0"
pruning-interval = "0"

2.On debian based systems if you are using wget you need to escape special characters  eg:```wget https://storage.googleapis.com/download/storage/v1/b/provenance-mainnet-backups/o/latest-data.tar.gz\?generation\=1658435717801489\&alt\=media```

**Comment by debasish22** [comment]
Hello @arnabmitra When we are trying to decode the transactions of "execute contract" type using the tool it shows invalid transaction but these are valid ones as per explorer. Validated the hashes also its base64 only. Can you please help here with this issue.

./build/decode-piobase64tx Cq4CCqsCCiQvY29zbXdhc20ud2FzbS52MS5Nc2dFeGVjdXRlQ29udHJhY3QSggIKKXBiMWV2ZGpqY2FnbGxneWYyM3B6ZjdlMmdrdmZ1YWtlZ3NudjQ5eWhqEilwYjE4dmQ4ZnB3eHpjazkzcWx3Z2hhajZhcmg0cDdjNW44OTR2bnU1ZxqpAXsiZXhlY3V0ZV9tYXRjaCI6eyJhc2tfaWQiOiJlOTU3OGU1ZC0xYzY5LTQ5ZmYtOWRiNC01MjU1MGUxZmJjYTUiLCJiaWRfaWQiOiJhYTkwNTI4Yy01YjAyLTRiMDgtYjAyMS0yMGYyNzFmNGFhNjkiLCJwcmljZSI6IjAuMDAwMDAwMDExODAwMDAwMDAwIiwic2l6ZSI6IjQyMzAwMDAwMDAwMDAifX0SbQpRCkYKHy9jb3Ntb3MuY3J5cHRvLnNlY3AyNTZrMS5QdWJLZXkSIwohApCjzE2HSfpcR0hEnpu0N6Unv9wuyCuWyhPef4tRjOUSEgQKAggBGMIbEhgKEgoFbmhhc2gSCTQ3OTgxNjE2MBDgrw8aQC0cGU3VkmLCYSxC0hWv6gR/wgq6G402zimiHvlXZtgxXG6l1SXOxGE6RDZ/RakHPjfDWF3GVIbTCiJgTrp/7Gk=

./build/decode-piobase64tx CrACCq0CCiQvY29zbXdhc20ud2FzbS52MS5Nc2dFeGVjdXRlQ29udHJhY3QShAIKKXBiMXVxMnJwOGdydjRsNnRwOHh6YW5hZHZ1c3NkZWx6enhuMGZsY3FyEilwYjE4dmQ4ZnB3eHpjazkzcWx3Z2hhajZhcmg0cDdjNW44OTR2bnU1ZxqRAXsiY3JlYXRlX2FzayI6eyJpZCI6IjRmMjI0ODAzLTYzNjQtNGFhOS05N2I4LTVhZjZkZjY0YzZmYyIsInByaWNlIjoiMC4wMDAwMDAwMDM3IiwicXVvdGUiOiJjZmlndXJlb21uaSIsImJhc2UiOiJuaGFzaCIsInNpemUiOiIyNjAwMDAwMDAwMDAwMDAifX0qGAoFbmhhc2gSDzI2MDAwMDAwMDAwMDAwMBJtClAKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDucLLqe4Ctun410s/vOAuSllZHUU3TdUee0bILHqLRHQSBAoCCAEYJhIZChMKBW5oYXNoEgozMDEwNTc2Mjc1EKelExpAx8Fvc/1hBoQ+x/E6bvttVaZCI8zFJIxXiyEp3p3Ltv9KvR3o0kIvVuQMQhxOaElh6tFg9l7ia3CyNBbY+2jlLw==



https://explorer.provenance.io/tx/0E9B0967822FE5BC87BA3872DDA23D45697B50E1AEA6C0CE74DBE793C9331BD4
https://explorer.provenance.io/tx/2192F4FAD274CB07BF2339535AB03FF8CE56356931DE578F55B2A2887819FC34

**Comment by iramiller** [comment]
you are going to need to do some leg work to use that decoder with older versions of the chain ... namely you will need to match the versions of the Cosmos SDK, ibc, cosmwasm, and provenance in the piotxdecoder with the versions at the blockheight you are trying to read the content of.  

For the transaction samples above the provenance version was 1.7.x at the time those blocks were written ... update the source code of your tool to match the versions we use in 1.7.x so your type signatures match what was used back then.

These versions can be seen in the go.mod file ....
https://github.com/provenance-io/provenance/blob/v1.7.6/go.mod

**Comment by arnabmitra** [comment]
@debasish22  responded to you on discord a couple of days ago, 
to re-iterate .. the explorer is our official tool to pull in txs.. what i showed you was an example on how you could write your own code to parse tx's if you wanted, i do not maintain that project with latest protos or not backward compatible protos.. having said that i did update the project with the wasm proto required to decode that block tx  now .. 
./build/decode-piobase64tx CrACCq0CCiQvY29zbXdhc20ud2FzbS52MS5Nc2dFeGVjdXRlQ29udHJhY3QShAIKKXBiMXVxMnJwOGdydjRsNnRwOHh6YW5hZHZ1c3NkZWx6enhuMGZsY3FyEilwYjE4dmQ4ZnB3eHpjazkzcWx3Z2hhajZhcmg0cDdjNW44OTR2bnU1ZxqRAXsiY3JlYXRlX2FzayI6eyJpZCI6IjRmMjI0ODAzLTYzNjQtNGFhOS05N2I4LTVhZjZkZjY0YzZmYyIsInByaWNlIjoiMC4wMDAwMDAwMDM3IiwicXVvdGUiOiJjZmlndXJlb21uaSIsImJhc2UiOiJuaGFzaCIsInNpemUiOiIyNjAwMDAwMDAwMDAwMDAifX0qGAoFbmhhc2gSDzI2MDAwMDAwMDAwMDAwMBJtClAKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDucLLqe4Ctun410s/vOAuSllZHUU3TdUee0bILHqLRHQSBAoCCAEYJhIZChMKBW5oYXNoEgozMDEwNTc2Mjc1EKelExpAx8Fvc/1hBoQ+x/E6bvttVaZCI8zFJIxXiyEp3p3Ltv9KvR3o0kIvVuQMQhxOaElh6tFg9l7ia3CyNBbY+2jlLw==
{"body":{"messages":[{"@type":"/cosmwasm.wasm.v1.MsgExecuteContract","sender":"pb1uq2rp8grv4l6tp8xzanadvussdelzzxn0flcqr","contract":"pb18vd8fpwxzck93qlwghaj6arh4p7c5n894vnu5g","msg":{"create_ask":{"id":"4f224803-6364-4aa9-97b8-5af6df64c6fc","price":"0.0000000037","quote":"cfigureomni","base":"nhash","size":"260000000000000"}},"funds":[{"denom":"nhash","amount":"260000000000000"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A7nCy6nuArbp+NdLP7zgLkpZWR1FN03VHntGyCx6i0R0"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"38"}],"fee":{"amount":[{"denom":"nhash","amount":"3010576275"}],"gas_limit":"316071","payer":"","granter":""}},"signatures":["x8Fvc/1hBoQ+x/E6bvttVaZCI8zFJIxXiyEp3p3Ltv9KvR3o0kIvVuQMQhxOaElh6tFg9l7ia3CyNBbY+2jlLw=="]}
