### ISSUE TITLE
Upgrade provenance to use our Cosmos-SDK fork's `v0.46.1-pio-1-rc1`.

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#995]
Bump Cosmos-SDK to `v0.46.0-pio-1-rc4` (from `v0.45.5-pio-1`).

**Comment by SpicyLemon** [comment]
A couple issues were found with `rc1`. They were fixed and are now in `rc2`. So now that's the goal of this ticket.
Fixes:
* [222](https://github.com/provenance-io/cosmos-sdk/pull/222): Create the authz GetAuthorization function
* [223](https://github.com/provenance-io/cosmos-sdk/pull/223): Create IMsgServiceRouter interface and baseapp.SetMsgServiceRouter function

**Comment by SpicyLemon** [comment]
I've currently got it pulling in a local `wasmd` that has been updated to use Cosmos v0.46. But that's just a draft PR and isn't tagged yet or anything.

The issue: https://github.com/CosmWasm/wasmd/issues/927
The Draft PR: https://github.com/CosmWasm/wasmd/pull/930

We might have to pull that into our own `wasmd` fork and tag it so we can start moving forward.

**Comment by SpicyLemon** [comment]
Okay. I've got most of the unit tests ironed out. There's still a couple stragglers, and then one giant mess with the msg fees antehandler. Cosmos moved a lot of stuff around and as I've got things now, it looks like things are sometimes being charged twice. I'll have to really dig in and see how our stuff meshes with the new stuff and what changes need to be made.

**Comment by SpicyLemon** [comment]
In our fork of [wasmd](https://github.com/provenance-io/wasmd), I copied the draft PR branch from https://github.com/CosmWasm/wasmd/pull/930 and created branch `prov/v0.28.0-w-sdk-0.46.0` from it, and tagged it as `v0.28.0-pio-1-rc1`. That will let us at least move forward without everyone needed a local copy of that.

**Comment by SpicyLemon** [comment]
Needed to inject history and update swagger. So `rc4` was cut.

**Comment by kwtalley** [comment]
There was a bug in the wasmd version where contract instantiation would cause an overflow with gas calculation. There's a version from notional-labs that is being used by the community since 0.46 sdk isn't officially supported

source: https://github.com/CosmWasm/wasmd/pull/938
project status: https://github.com/CosmWasm/wasmd/issues/941
